### PR TITLE
Remove channel manager

### PR DESCRIPTION
**Pull request by solivier**
```
| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | No
| Added Behats                      | No
| Changelog updated                 | Yes
| Review and 2 GTM                  | No
```

### CODE REVIEW

**Comment by jjanvier** [comment]
really weird for me
you have a UI channel repo that is used everywhere except in the UI
it's used in domain services... (reader, processor, writer...)

**Comment by ClementGautier** [comment]
GTM

**Comment by jjanvier** [comment]
gtm

**Comment by ClementGautier** [comment]
1.5 is about to be released and no more "nice to have" BC breaks are allowed. Please reopen this PR on the master branch for the upcoming 1.6.

**Pull request closed without merging**
