### PR TITLE
Add some rules in phpcs fixer according to our code style rules

### PR DESCRIPTION
**Pull request by ahocquard**
[//]: <> (<3 Thanks for taking the time to contribute! You're awesome! <3)

[//]: <> (If you've never contributed to this repository before, please read https://github.com/akeneo/pim-community-dev/blob/master/.github/CONTRIBUTING.md)

**Description (for Contributor and Core Developer)**

[//]: <> (What does this Pull Request do? reference the related issue?)
Following our rules, phpcs fixer is not strict enough.
Here an improvement:

- prevent double blank lines
- enforce blank line before return statement

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | -
| Added Behats                      | -
| Added integration tests           | -
| Changelog updated                 | -
| Review and 2 GTM                  | -
| Micro Demo to the PO (Story only) | -
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

### CODE REVIEW

**Comment by jjanvier** [comment]
Personally I'm against that.
I find it useless and counter productive.

As explained in much more detailed way [here](https://github.com/akeneo/pim-community-dev/pull/4449#issuecomment-218776359) and [there](https://github.com/akeneo/pim-community-dev/pull/6082#issuecomment-295179178).

But let the team vote.

**Comment by ahocquard** [comment]
@jjanvier so, why are we still commenting about blank line or blank return statement?
I'm not a robot (and don't want to be ;)).

Btw, it's in our coding standard: https://docs.akeneo.com/1.7/reference/best_practices/core/standards.html#naming-conventions.

```
Add a comma after each array item in a multi-line array, even after the last one;
Add a blank line before return statements, unless the return is alone inside a statement-group (like an if statement);
````
(and probably some other rules)

But thanks to this PR, I will no fix anymore blank lines. Tired of bikeshedding.

**Comment by jjanvier** [comment]
I'm not commenting anything related to that. People who do are imho wrong. 

I'm not a robot neither. We already have cs-fixer running on the CI. We don't need the review of anybody regarding CS. Sometimes there are blank lines before return statements and, what's the problem? Somebody doesn't like, too bad. It's OK with our standard, PSR2. It's not necessary to comment such things. When I see such a thing, I omit it deliberately. 

Imo, for each CS problem a teammate wants to report in a PR, he should instead hold himself back and find something meaningful instead.

Again, as explained many times, (and in the links I provided) I'm not at all against a CS. I'd just like we stick to a standard. PSR2 or SF style, whatever. 

But again, I let the team vote.

**Comment by aRn0D** [comment]
Those changes are a subpart of Symfony convention. I would rather use Symfony convention and never comment CS.

**Comment by ahocquard** [comment]
@jjanvier @aRn0D so we can delete it in our coding standard in the documentation, right?

**Pull request closed without merging**
