### PR TITLE
PIM-3634 : Allow fillField() to remove multiselect values

### PR DESCRIPTION
**Pull request by grena**
| Q                    | A
| -------------------- | ---
| Bug fix?             | N
| New feature?         | N
| BC breaks?           | N
| CI currently passes? | Y
| Tests pass?          | Y
| Scenarios pass?      | Y
| Checkstyle issues?*  | N
| PMD issues?**        | N
| Changelog updated?   | N
| Fixed tickets        | PIM-3634
| DB schema updated?   | N
| Migration script?    | N
| Doc PR               | -

### CODE REVIEW

**Comment by nidup** [comment]
maybe a good timing to explode this huge method to smaller protected methods with explicit naming to improve the readability :)

**Comment by grena** [comment]
Yes, very good idea ! I'm digging this ;)

**Comment by sumbobyboys** [comment]
Nice PR ! Especially with the big split :)

**Comment by nidup** [comment]
Far more readable, GG

**Comment by nidup** [comment]
GTM once CI green

**Comment by grena** [comment]
Thanks ! CI's green, behat ok !

**Pull request merged**
