### PR TITLE
PIM-7456: Security vulnerabilities in dependencies

### PR DESCRIPTION
**Pull request by arnolanglade**
**Description (for Contributor and Core Developer)**

Solve https://github.com/akeneo/pim-community-dev/issues/8329

The PIM used and extended `APYJsFormValidationBundle` which is not maintained since 5 years. It was used to enable JS validation on the front end. This bundles use another bundle which have security vulnerabilities. The solution to avoid this vulnerabilities was to remove this bundle and the bundle we created to customize/extend it. To remove it we copy paste the JS code generated by this bundle in the template. Sometimes we did not do that because the data validation was done by the back end (all creation popin, for instance).

Doctrine bundle had some security vulnerabilities too, we dump from 1.2.x to 1.9.x. The only thing we had to do was to update the configuration (adding server_version).

Seb fixed some memory issues during the PIM installation too.

Impacted form:
- attribute group
- category
- familly creation
- group creation
- group type creation
- group type edit
- mass edit configuration
- variant group creation
- role update
- user update

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | -
| Added legacy Behats               | -
| Added acceptance tests            | -
| Added integration tests           | -
| Changelog updated                 | yes
| Review and 2 GTM                  | Todo
| Micro Demo to the PO (Story only) | -
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

### CODE REVIEW

**Comment by fitn** [comment]
Are you sure it is absolutely mandatory? By the past, we already got troubles updating doctrine for instance. I don't know what these updates fix but I am not confident with this kind of update for another reason than identified bug.

**Comment by arnolanglade** [comment]
CI is green for CE edition: https://ci.akeneo.com/blue/organizations/jenkins/akeneo%2Fpim-community-dev/detail/PR-8402/20/pipeline/18 (The build for the EE: https://ci.akeneo.com/blue/organizations/jenkins/akeneo%2Fpim-enterprise-dev/detail/PR-4158/7/pipeline/117)

**Comment by arnolanglade** [comment]
One fail but it is not related to this PR. The scenario is unstable but it passes if you let the time to selenium enough time to find the element.

**Comment by arnolanglade** [comment]
I ran a CI this morning, a scenario failed, I ran it locally and it passed.

**Pull request merged**
