### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by wa-daniel-fahl**
**Description (for Contributor and Core Developer)**

XLSX product export did not allow selection of decimal separator due to a copy&paste error in the form extension configuration.
Fixed by using the correct key and parent for the form element in both edit and show form.

### CODE REVIEW

**Comment by pierallard** [comment]
Hi @wa-daniel-fahl and thanks for your Pull Request :dancer: :tada: !
Did you sign the Contribution Agreement so we can merge your PR ?
https://www.akeneo.com/contributor-license-agreement/
Regards
Pierre

**Comment by wa-daniel-fahl** [comment]
Hi @pierallard,

yes, now I have signed the Contribution Agreement.

Thanks,
Daniel

**Comment by pierallard** [comment]
I ran a build on our continuous integration platform to be sure there is no regression with you PR, then we will be able to merge it.
Can you add a last commit to the CHANGELOG-1.7 please ?
Take example on this file (first entry)
https://raw.githubusercontent.com/akeneo/pim-community-dev/master/CHANGELOG-2.2.md
(And don't forgot to add "1.7.x" in the header of the file to be released on the next version).
If you didn't understand, just ask, I will add it myself.

**Comment by wa-daniel-fahl** [comment]
Sorry, I really don't understand what I am supposed to commit where...
Would you mind adding it? Thanks a lot!

**Comment by pierallard** [comment]
I just did it :)

**Comment by damien-carcel** [comment]
And it is finally merged. Thank you so much for this PR @wa-daniel-fahl .

**Pull request merged**
