### PR TITLE
Documentation: Broken links on README.md

### PR DESCRIPTION
**Pull request by Freyskeyd**
**Description (for Contributor and Core Developer)**

This PR solve some broken links on the README.

Signed-off-by: Freyskeyd <simon.paitrault@gmail.com>

### CODE REVIEW

**Comment by juliensnz** [comment]
@Freyskeyd hey! thanks a lot for this PR, it's validated and will be merged as soon as you sign this agreement: https://www.akeneo.com/contributor-license-agreement/

**Comment by jmleroux** [comment]
@juliensnz , is it not already done ?

> Signed-off-by: Freyskeyd simon.paitrault@gmail.com

**Comment by Freyskeyd** [comment]
I just signed it.

**Comment by juliensnz** [comment]
Merged, thanks a lot!

**Comment by juliensnz** [comment]
You can now claim a badge on http://badger.akeneo.com :)

**Pull request merged**
