### PR TITLE
Quick export: Add unit column für empty metrics

### PR DESCRIPTION
**Pull request by Hocdoc**
This fixes our issue #3595.

### CODE REVIEW

**Comment by jmleroux** [comment]
Hi @Hocdoc 

Is it possible for you to fix the PHPspecs before i run the CI with your branch ?

Regards,
JM

**Comment by Hocdoc** [comment]
I've now added the PHPspecs.

(For my next PR I promise that I will read the CONTRIBUTING doc before. ;-) )

**Comment by jmleroux** [comment]
Thank you for fixing specs and sorry for the delay.
I will run the CI on this nice PR.

**Comment by jmleroux** [comment]
Hi @Hocdoc ,

This PR is breaking 8 features in CE ORM : 

Export products.Successfully export products to multiple channels
Export products.Do not export products that are not classified
Export products.Export only attributes with the locale specific
Export products.Export decimal attributes with the correct decimals formatting
Export products.Export metric attributes with the correct decimals formatting
Export products.Successfully export products and be able to download exported file
Export products.Successfully export products with heterogeneous data
Export products with ordered options.Export products with options ordered by sort order

Is it possible for you to run them locally in order to fix it ?

Regards,
JM

**Comment by jmleroux** [comment]
Here is the log for the failing build : 

[1902-build.txt](https://github.com/akeneo/pim-community-dev/files/147940/1902-build.txt)

**Comment by nidup** [comment]
GTM

**Comment by nidup** [comment]
Merged :tada: thank you @Hocdoc ! (and sorry again for the delay)

**Comment by pierallard** [comment]
Hey @Hocdoc ! Thanks for this PR. We just merged it ! :tada: 
Sorry for the looooong time it takes. We're working to merge contributions faster.
FYI, we just added one commit to keep the continous integration behats green, if you want to take a look, it was easy ; https://github.com/akeneo/pim-community-dev/commit/37cd3a48af723dfe86e2f20873445f1758318eb4

Thanks again!

**Comment by Hocdoc** [comment]
Ok, thanks for merging and fixing the CI!

**Pull request merged**
