### PR TITLE
 [BUGFIX] Issue while editing user profile because "name" doesn't exis...

### PR DESCRIPTION
**Pull request by diglin**
…t in UserBundle class

**Description (for Contributor and Core Developer)**

Fix following issue due to commit https://github.com/akeneo/pim-community-dev/commit/0c484a97138a59249df049acbe114037593c772f:

```
request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "Neither the property "name" nor one of the methods "name()", "getname()"/"isname()" or "__call()" exist and have public access in class "PimEnterprise\Bundle\UserBundle\Entity\User"." at /home/akeneo/pim/vendor/akeneo/pim-community-dev/src/Pim/Bundle/UserBundle/Resources/views/User/update.html.twig line 158

{"exception":"[object] (Twig_Error_Runtime(code: 0): Neither the property \"name\" nor one of the methods \"name()\", \"getname()\"/\"isname()\" or \"__call()\" exist and have public access in class \"PimEnterprise\\Bundle\\UserBundle\\Entity\\User\". at /home/akeneo/pim/vendor/akeneo/pim-community-dev/src/Pim/Bundle/UserBundle/Resources/views/User/update.html.twig:158)"}
```

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | Todo
| Added legacy Behats               | Todo
| Added acceptance tests            | Todo
| Added integration tests           | Todo
| Changelog updated                 | Todo
| Review and 2 GTM                  | Todo
| Micro Demo to the PO (Story only) | Todo
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

### CODE REVIEW

**Comment by diglin** [comment]
In https://github.com/akeneo/pim-community-dev/commit/0c484a97138a59249df049acbe114037593c772f there is no front test, I don't even know how this flash message react or can be triggered.

**Comment by oliverde8** [comment]
This bug is also present in the 2.0 version.

**Comment by KarenMayo** [comment]
Hello @diglin 

Thanks for the PR, but as  as mentioned in the https://akeneo.atlassian.net/browse/SDS-3799 opened by you, when editing a user in EE, the tab's title is not properly set, it appears as "User {{ username }} | Edit", but it does not prevent the edition of the user's profile. This is not the cause of the behavior you are getting, but probably related to local issue on your side.

Our Mainteance team will have a look at the issue related to the title of the tab, I will let you know as soon as the fix is available.

Regards,

Karen

**Comment by diglin** [comment]
Hi @KarenMayo ok thank you for your feedback

**Pull request closed without merging**
