### PR TITLE
Reference documentation

### PR DESCRIPTION
**Pull request by jjanvier**
With this PR I propose to move all files related to "documentation" into a dedicated folder.

It's not our official docs.akeneo.com files, so I didn't call it `doc`. I propose reference documentation `reference_doc`. Don't hesitate to suggest better names.

What could go in this folder? 
 - This PR for instance https://github.com/akeneo/pim-community-dev/pull/7633. I'll try to finish it this week :/
- Anything that could help the development team but is not official documentation.

### CODE REVIEW

**Comment by jjanvier** [comment]
`internal_doc`?

**Comment by jjanvier** [comment]
`development_doc`?

**Comment by damien-carcel** [comment]
`internal_doc` or `technical_doc`.

**Comment by ahocquard** [comment]
I prefer "internal_doc" as it's a little bit more generic, allowing to put some things like scalability, implementation choices, etc.

**Comment by jjanvier** [comment]
I renamed the folder to `internal_doc`

**Pull request merged**
