### PR TITLE
Fixed PHP 7.1 static analysis fatal error

### PR DESCRIPTION
**Pull request by gplanchat**
**Description (for Contributor and Core Developer)**

Addresses an error in Travis CI on PHP 7.1 :

```
Fatal error: Declaration of Pim\Bundle\CatalogBundle\Doctrine\ORM\Repository\ChannelRepository::findBy(array $criteria, array $orderBy = Array, $limit = NULL, $offset = NULL) must be compatible with Doctrine\Common\Persistence\ObjectRepository::findBy(array $criteria, ?array $orderBy = NULL, $limit = NULL, $offset = NULL) in /home/travis/build/akeneo/pim-community-dev/src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ChannelRepository.php on line 19
```

**Definition Of Done (for Core Developer only)**

| Q | A |
| --- | --- |
| Added Specs |  |
| Added Behats |  |
| Changelog updated |  |
| Review and 2 GTM |  |
| Micro Demo to the PO (Story only) |  |
| Migration script |  |
|  Tech Doc |  |

### CODE REVIEW

**Comment by nidup** [comment]
Hi @gplanchat 

thx for the PR, there are still issues with PHP 7.1 build, do you plan to fix all issues in this PR? if yes, don't hesitate to change the travis ci matrix to make PHP 7.1 mandatory ;)

**Comment by gplanchat** [comment]
Hi @nidup,

Remaining issues seems at first sight to be inside the Symfony version used :

```
notice: A non well formed numeric value encountered in
      /home/travis/build/akeneo/pim-community-dev/vendor/symfony/symfony/src/Symfony/Component/Validator/Constraints/File.php
      line 97
```

I'll check later if it requires a framework version upgrade.

**Comment by nidup** [comment]
Exact! so we can't fix these for now ;) 

Please fix my couple of comments and I'll merge this first PR :tada: :tada:

**Comment by gplanchat** [comment]
At this time, there is no PHP 7.1 official support in Symfony, even on 3.1

**Comment by nidup** [comment]
ok, so we're not late at least ;)

**Comment by gplanchat** [comment]
It has been fixed in https://github.com/symfony/symfony/commit/07467ed3a3aca5bd8760060e4472cf519b7812c5#diff-5856376f5de956cee665e98d9b9525a6L91 which seems to be on symfony/symfony >= 2.7.16

**Comment by gplanchat** [comment]
I was almost thinking about forking Symfony framework when I saw the dependency hell rising ;)

**Comment by nidup** [comment]
Yeah! thank you for the PR and the dependencies bump.

I'm trying to run your branch on our jenkins continuous integration but I encounter an issue during the build, I discuss with the team and I'll keep you posted soon, once I have the CI running properly and the couple of comments regarding `['label' => 'ASC'"]` will be fixed, I'll merge! :tada:

**Comment by nidup** [comment]
Hi @gplanchat 

Thanks to @damien-carcel I know why your CI is failing running your PR, it looks like the PIM is not installable,

```
Create session table Load jobs for fixtures. The command terminated with an error code: 1. Error during PIM installation. The command terminated with an error code: 1.    Error Output: [Doctrine\ORM\ORMException]     Unrecognized field: label
```

Pretty sure it's related to the comment I made regarding the code to label change in the repository, are you able to install it locally?

**Comment by gplanchat** [comment]
I'm checking again the install with PHP 7.1

**Comment by damien-carcel** [comment]
Beware, I didn't test with PHP 7.1, but with PHP 5.6, which is the version we officially support, and for the moment the only one that run on our CI.

**Comment by gplanchat** [comment]
My bad, I put the wrong field name in the locale repository

**Comment by nidup** [comment]
Thank for the fix, I'm running our builds and keep you posted :)

**Comment by nidup** [comment]
Hi @gplanchat,

Sadly, with this change, I have 50 broken behat scenario in the community edition, I reproduced the issue by bumping the dependencies,

```
Browse association types.Successfully view, sort and filter association types
Filter attributes.Successfully filter attributes
Delete an attribute.Sucessfully delete and recreate a text attribute used in a product and filter on it
Browse channels.Successfully view, sort and filter channels
Browse currencies.Successfully view, sort and filter currencies
Browse currencies.Successfully activate a currency
Products back to the grid.Successfully restore filters without hashnav
Products back to the grid.Successfully restore filters with hashnav
Products back to the grid.Successfully restore the scope dropdown
Add attributes to a variant group.Remove an attribute which is linked to a variant group
Browse variant groups.Successfully view, sort and filter variant groups
Filter available products for a variant group.Successfully filter the product datagrid when I edit a variant group
Browse export executions.Successfully view, sort and filter export executions
Browse export profiles.Successfully view and sort export jobs
Browse families.Successfully display all the families
Filter group types.Successfully filter group types
Browse imports.Successfully filter import jobs with values
Validate values for unique attributes when importing products.Import a file with same value in unique attribute and with existing product with this value
Validate values for unique attributes when importing products.Import a file with same sku, duplicated products should not be imported
Browse locales.Successfully view, sort and filter locales
Edit common attributes of many products at once.Successfully mass edit products on the non default channel
Apply a mass action on all entities.Edit all families, filtered by name
When I mass edit I should be able to see how many items will be edited.Successfully count the number of mass-edited items when using filters and select all action
Associate a product.Keep product associations grids context
Filter products.Successfully filter products
Filter products.Successfully filter products with the sames attributes
Filter products.Successfully filter product without commons attributes
Filter products.Successfully filter only one product
Filter products by date field.Successfully filter products by empty value for date attribute
Filter products by date field.Successfully filter products by date attributes
Filter products by date field.Filter products by date attributes and keep the appropriate default filter values
Filter products per media.Successfully filter products by image and file attributes
Filter products by number field.Successfully filter products by empty value for number attributes
Filter products by text field.Successfully filter products by empty value for text and textarea attributes
Filter products by text field.Successfully filter products by empty value for localizable text attribute
Filter products by text field.Successfully filter products by empty value for scopable text attribute
Filter products by text field.Successfully filter products by empty value for scopable and localizable text attribute
Filter products with multiples metrics filters.Successfully filter products with the sames attributes
Filter products with multiples metrics filters.Successfully filter only one product
Filter products with multiples number fields filters.Successfully filter products with the sames attributes
Filter products with multiples number fields filters.Successfully filter product without commons attributes
Filter products with multiples prices filters.Successfully filter product without commons attributes
Filter products with multiples text fields filters.Successfully filter products with the sames attributes
Filter products with multiples text fields filters.Successfully filter product without commons attributes
Browse product groups.Successfully view, sort and filter product groups
Filter products per metric.Successfully filter products by metric
Filter products per price.Successfully filter products by price
Filter products by text field.Successfully filter products with special characters value for text attribute
Filter products with multiples metrics filters.Successfully filter product without commons attributes
Filter products with multiples prices filters.Successfully filter products with the sames attributes
```

I think that the main issue is that the grid filters are broken, before to update deps, we have, 

normal-grid

After to update deps we have,

broken-grid

Let me know if you want / have time to investigate further on this issue.

Thank you,

**Comment by gplanchat** [comment]
Yes, I reproduced it on my side. It seems to be present only on a subset of filters.

I'm checking.

**Comment by gplanchat** [comment]
I did not find yet where the labels were transformed into numbers.

**Comment by nidup** [comment]
Without checking to much I'd say into the FilterBundle because we do real weird stuff with form types with "hacked" form views rendering

**Comment by damien-carcel** [comment]
Hi @gplanchat . I am closing your PR as this issue is now fixed on master.

Here is the link of the corresponding PRs:
- Symfony upgrade: https://github.com/akeneo/pim-community-dev/pull/5521
- PHP 7.1 related fixes: https://github.com/akeneo/pim-community-dev/pull/5539 

Sorry, we were in a hurry upgrading, and I forgot you started something too. At least, you will know why those labels were not working anymore ;-).

Cheers,
Damien

**Pull request closed without merging**
