### PR TITLE
PIM-5978: Fix missing currencies

### PR DESCRIPTION
**Pull request by ahocquard**
**Description (for Contributor and Core Developer)**

The goal of this PR is to add missing valid currencies, due to a regression in the refactoring of the currency loader in the 1.6 version.

In 1.5 version, all currencies are loaded from Intl, except the currencies in the file  "currencies.csv", in the list "removed_currencies".

This list of removed currencies is therefore a black list.

In 1.6 version, all currencies are loaded from the file "currencies.csv" (and not from Intl): this file is not a black list anymore, but a white list of the currencies to load. 
However, the list of removed currency has been kept in this file (+ EUR and USD), and valid currencies have not been added.

=> 1.6 version load only deprecated currencies (+USD and EUR) and not valid currencies.

Because a customer could have already used those deprecated currencies in the 1.6.X version, we will not remove those in the file "currencies.csv". 
Valid currencies are added in the file. Therefore, both deprecated and valid currencies will be loaded.

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       |n
| Added Behats                      |y
| Changelog updated                 |y
| Review and 2 GTM                  |y
| Micro Demo to the PO (Story only) |n
| Migration script                  |n
| Tech Doc                          |n

### CODE REVIEW

**Comment by juliensnz** [comment]
Could you please change your github picture?

**Comment by juliensnz** [comment]
@BitOne as this only define the possible list of currencies, it will not affect performances. Only activated currencies are listed on the application. We should not have problem with this modification.

**Comment by nidup** [comment]
Same fix to apply on enterprise edition then GTM

**Comment by BitOne** [comment]
@juliensnz I know, but this currencies will be in the table at the end, right ? And there's a lot of place where we do some query on is_activated. We may have some place where we loop through the locale and check isActivated().
So it's possible that this change has impact on performances, so could be interesting to check this point.

**Comment by ahocquard** [comment]
@BitOne I don't notice any performance issue with the currencies settings menu, but I have not check with import. Actually, there were 200 currencies in the 1.5 version, so technically it's 50% more. Is an import check really important, considering that point ?

**Comment by ahocquard** [comment]
I have imported 1000 products. Without my patch : 1m29, with my patch 1m32 (3%). It seems it has no impact, at least on the imports.

**Pull request merged**
