### PR TITLE
Add loader mask on file upload on job launch

### PR DESCRIPTION
**Pull request by simoncarre**
[//]: <> (<3 Thanks for taking the time to contribute! You're awesome! <3)

[//]: <> (If you've never contributed to this repository before, please read https://github.com/akeneo/pim-community-dev/blob/master/.github/CONTRIBUTING.md)

**Description (for Contributor and Core Developer)**

Add loader mask on file upload on job launch.

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | -
| Added Behats                      | -
| Added integration tests           | -
| Changelog updated                 | -
| Review and 2 GTM                  | -
| Micro Demo to the PO (Story only) | -
| Migration script                  | -
| Tech Doc                          | -

### CODE REVIEW

**Comment by juliensnz** [comment]
Wow, nice contribution! We will take a look at it and come back to you ASAP!

**Comment by SamirBoulil** [comment]
Hello ! 

First of all, thank you for raising this issue! it is indeed a bug that has to be fixed.

But unfortunately we won't be able to merge this PR "as-is":
This screen has been refactored and a new way of showing the loading mask has been introduced.

I started a new PR in the Akeneo repository (that is highly inspired by this fix, so again thank you ^^)
see https://github.com/akeneo/pim-community-dev/pull/6174.

Regarding your contribution - and even if we don't merge your code "as-is" - you can claim the "Core Contributor" badge on http://badger.akeneo.com !

**Comment by simoncarre** [comment]
Thanks @SamirBoulil!

I just claimed the "Core Contributor" badge :wink:

**Comment by grena** [comment]
@simoncarre Unlocked! GG :)

**Pull request closed without merging**
