### PR TITLE
Added a new measure family for food products and food supplements. Extended Duration family.

### PR DESCRIPTION
**Pull request by JulienDotDev**
**Description (for Contributor and Core Developer)**

This new measure unit is used to store legal informations about food products and food supplements.
This extend the duration family to add three units : week, month (conversion value could be discussed), year.

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       |
| Added Behats                      |
| Changelog updated                 |
| Review and 2 GTM                  |
| Micro Demo to the PO (Story only) |
| Migration script                  |
| Tech Doc                          |

### CODE REVIEW

**Comment by nidup** [comment]
Hi @JulienDotDev 

Thank you for your contribution :tada: 

I double checked for Energy family and it seems ok (cf https://en.wikipedia.org/wiki/Calorie).

FYI, you don't need to add any translations, we add only english keys, then translations are merged from Crowdin each week.

I'm running our continuous integration then I'll merge :+1: 

Cheers

**Comment by jmleroux** [comment]
@JulienDotDev ,

if your interested in new measures, you could also check this WIP bundle.
We are adding a lot of new unit to be able to import from different sources. Do not hesitate to give feedback if you have time.
https://github.com/akeneo/ExtendedMeasureBundle/tree/add_units/src/Resources/config/measures

**Comment by nidup** [comment]
Hi @JulienDotDev 

Merged! :tada: :tada: 

As you're now a core contributor don't hesitate to claim this brand new badge http://badger.akeneo.com/badge/41acec2c-649f-11e6-92dc-d60437e930cf :wink: 

PS: yep, forgot to warn you but the marketplace team is creating an extended measure bundle to cover new measure needs in the v1.6 without having to wait for the upcoming v1.7 to be released (as we never add new features in an already released version), thx @jmleroux for the comment :)

**Comment by JulienDotDev** [comment]
Hi Nicolas,

thanks for the merge, glad to achieve my first contribution.

@jmleroux @nidup I'll check the measure bundle when i'll have time, thanks ;)

**Pull request merged**
