### PR TITLE
Added a new measure family for case boxes packaging

### PR DESCRIPTION
**Pull request by gplanchat**
**Description (for Contributor and Core Developer)**

This new measure unit makes it possible to use a metric for case boxes packaging information.

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       |
| Added Behats                      |
| Changelog updated                 |
| Review and 2 GTM                  |
| Micro Demo to the PO (Story only) |
| Migration script                  |
| Tech Doc                          |

### CODE REVIEW

**Comment by nidup** [comment]
Hi @gplanchat !

Thx for the contribution :tada: 

I run our continuous integration ;)

Cheers

**Comment by nidup** [comment]
Hi @gplanchat 

CI is all green! may you rebase your PR? (then I'll merge)

You have conflicts with the "just merged" https://github.com/akeneo/pim-community-dev/pull/5132

Thx!

**Comment by jmleroux** [comment]
Hi @gplanchat ,

you can laso check this comment ;)
https://github.com/akeneo/pim-community-dev/pull/5132#issuecomment-254544839

**Comment by gplanchat** [comment]
Yep @jmleroux I already checked, @fitn deserves a specific badge for this ;)

The commits were rebased

**Comment by nidup** [comment]
Merged! :tada:

**Comment by a2xchip** [comment]
:)

Best Regards, Jeliuc Alexandr
http://about.me/ajeliuc

2016-10-19 10:43 GMT+03:00 Nicolas Dupont <notifications@github.com>:

**Pull request merged**
