### PR TITLE
Fix typo AsyncSelectType phpdoc

### PR DESCRIPTION
**Pull request by fitn**
It was just a typo... :)

### CODE REVIEW

**Comment by phaseinducer** [comment]
GTM

**Comment by jmleroux** [comment]
GTM (without CI)

**Comment by pierallard** [comment]
Please run the CI for 1.0, 1.2, 1.3, 1.4, 1.5, 1.6 and 1.7 with EE, CE, orm, odm then GTM.
:trollface:

**Comment by nidup** [comment]
thx! merged :)

**Pull request merged**
