### PR TITLE
PIM-5913: Unify user show and user edit

### PR DESCRIPTION
**Pull request by pierallard**
Add a cancel button, put the customer info into the very left.

screenshot from 2016-08-11 10 52 05

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | n
| Added Behats                      | n
| Changelog updated                 | n
| Review and 2 GTM                  | TODO
| Micro Demo to the PO (Story only) | y
| Migration script                  | n
| Tech Doc                          | n

### CODE REVIEW

**Comment by loicguillois** [comment]
GTM

**Comment by SamirBoulil** [comment]
GTM

**Comment by jjanvier** [comment]
then cancel "back" icon is weird

**Comment by jjanvier** [comment]
on the product grid you put it on the left a week ago
here it's inconsistent

**Pull request merged**
