### PR TITLE
[TR] PIM-5219: Include database name into entity references

### PR DESCRIPTION
**Pull request by phaseinducer**
Needed by : https://github.com/akeneo-labs/DirectToMongoDBBundle/pull/4

### CODE REVIEW

**Comment by sumbobyboys** [comment]
GTM

**Comment by skeleton** [comment]
GTM

**Comment by willy-ahva** [comment]
GTM

**Comment by jjanvier** [comment]
gtm once possible to merge on 1.4 :p

**Comment by solivier** [comment]
GTM

**Pull request merged**
