### PR TITLE
[TR] PIM-4309: Fix bug processing media with a file not found exception

### PR DESCRIPTION
**Pull request by solivier**
| Q                    | A
| -------------------- | ---
| Bug fix?             | Yes
| New feature?         | No
| BC breaks?           | No
| CI currently passes? | Yes
| Tests pass?          | Yes
| Scenarios pass?      | Running
| Checkstyle issues?*  | Running
| PMD issues?**        | No
| Changelog updated?   | Yes
| Fixed tickets        | PIM-4309
| DB schema updated?   | No
| Migration script?    | No
| Doc PR               | No

Missing specs

### CODE REVIEW

**Comment by sumbobyboys** [comment]
GTM

**Comment by jmleroux** [comment]
GTM

**Comment by willy-ahva** [comment]
GTM

**Comment by nidup** [comment]
GTM

**Pull request merged**
