### PR TITLE
Update akeneo_batch.yml sender email

### PR DESCRIPTION
**Pull request by julienanquetil**
**Description (for Contributor and Core Developer)**
When you get notification by mail after a batch import for example you didn't have the right sender defined in pim_parameters.yml n your mailbox. 

Not sure if it's "normal" or a miss, but in my mind it must use the master one.

### CODE REVIEW

**Comment by SamirBoulil** [comment]
Hello @julienanquetil  !

Thank you for your bug fix! I updated your PR and added a changelog entry.

I'll run the CI on it and have it merged real soon!

I'll keep you updated on this PR status.

**Comment by SamirBoulil** [comment]
Congratulations @julienanquetil ! Your PR has been merged !

🎉  Again, thank you for your contribution ! 

You can now claim your badge "Core contributor" on http://badger.akeneo.com if you don't already have it. ^^

If you wish to contribute again, don't hesitate to look at our github project board where we labeled all kinds of tasks to take on ! https://github.com/akeneo/pim-community-dev/projects/1

**Comment by julienanquetil** [comment]
I already got it ;) and in my mind it's already merged some month ago !!!

**Comment by SamirBoulil** [comment]
Sorry it took so long for such a small fix.

We are currently reorganising our teams to take better care of the contributions made in order to have them merged as soon and as easily as possible.

Do not hesitate to contact me if you want to make suggestions and I hope that from now contributions will be munch better handled.

:)

**Pull request merged**
