### PR TITLE
TIP-574: ease completeness extensibility

### PR DESCRIPTION
**Pull request by jjanvier**
| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | -
| Added Behats                      | -
| Changelog updated                 | -
| Review and 2 GTM                  | -
| Micro Demo to the PO (Story only) | -
| Migration script                  | -
| Tech Doc                          | -

### CODE REVIEW

**Comment by juliensnz** [comment]
GTM

**Comment by skeleton** [comment]
GTM

**Comment by willy-ahva** [comment]
GTM

**Comment by solivier** [comment]
gtm

**Pull request merged**
