### PR TITLE
[TR] PIM-4174 Add back to grid button

### PR DESCRIPTION
**Pull request by filipsalpe**

### CODE REVIEW

**Comment by jmleroux** [comment]
Dunno if using the `backspace`key for going back is the desired behavior.
If not, it should be part of this PR.

**Comment by filipsalpe** [comment]
Not related to this at all. Isn't that due to the browser?

**Comment by jmleroux** [comment]
Yep, and it's totally valid. So my comment is irrelevant.

**Comment by sumbobyboys** [comment]
GTM

**Pull request merged**
