### PR TITLE
PIM-5080: Fix abstract processor

### PR DESCRIPTION
**Pull request by solivier**
| Q                 | A
| ----------------- | ---
| Specs             | Yes
| Behats            | No
| Blue CI           | Running
| Changelog updated | No
| Review and 2 GTM  | No

### CODE REVIEW

**Comment by ClementGautier** [comment]
GTM if you add a spec ;)

**Comment by solivier** [comment]
the spec is in EE no sences to add a spec here as the error is handled in the case of yaml import

**Comment by ClementGautier** [comment]
yep, I noticed it later, I edited my comment

**Comment by grena** [comment]
GTM

**Comment by jjanvier** [comment]
GTM

**Pull request merged**
