### PR TITLE
Prevent the creation of session in the API and optimize session management in listeners

### PR DESCRIPTION
**Pull request by ahocquard**
[//]: <> (<3 Thanks for taking the time to contribute! You're awesome! <3)

[//]: <> (If you've never contributed to this repository before, please read https://github.com/akeneo/pim-community-dev/blob/master/.github/CONTRIBUTING.md)

**Description (for Contributor and Core Developer)**

When you request the API, you always create a new session (GET, POST, PATCH).
Therefore, the table `pim_session` has a lot of lines for nothing.
Moreover, it's not logic because an API should be stateless and a cookie is returned in the response.

**Cause:**

It's due to the fact that there are some listeners opening a session.
These listeners are useless for the API, because the standard format is not dependent on the user or the locale. The standard format always returns the same data.

- The first commit prevents this behavior. It will not return anymore a cookie in the API response, and it will not create a session in the database for each request.

- The second commit is an optimization.
When you call `$request->getSession()`, it always creates a session in the database, and lock it.
Then, every concurrent request is waiting to get this lock, and it blocks the whole process.

Several `getSession`are done in controllers, and I think we should let it like this.
But put it in listeners means that you always lock a session, even if your request does not use session anymore later.

Then, we should close it after use in listeners. 
The price to re-open a session in some controllers is not very high compared to lock the session for each request (using a session or not).

[//]: <> (What does this Pull Request do? reference the related issue?)

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | Todo
| Added Behats                      | -
| Added integration tests           | Todo
| Changelog updated                 | -
| Review and 2 GTM                  | Todo
| Micro Demo to the PO (Story only) | -
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

### CODE REVIEW

**Comment by jjanvier** [comment]
Honestly, I don't understand what problem you try to resolve. 

> Therefore, the table pim_session has a lot of lines for nothing.

Why is it a serious problem? I don't understand.

About the resolution of the problem. I'm really not fan of this kind of optimizations. When a new feature will be released, with the need to touch the request/session, nobody will know he'll have to do such a thing. And we'll get back to the original problem. 

To sum up my POV:
If the number of lines in `pim_session` *do* is problematic, isn't it better to remove the line before rendering the API response?
If the performance optimization *do* is significant, couldn't we find a way to apply it everywhere?

**Comment by jjanvier** [comment]
Maybe something to dig:
isn't it something configurable with Symfony?
aka: when I'm these routes, use a different session handler

**Comment by ahocquard** [comment]
It's just not normal to create a session for an anonymous user.
You can prevent it easily : http://symfony.com/doc/current/session/avoid_session_start.html
Imagine 10000 per hour of the API, creating 1000000 lines in 5 days for... nothing.

I don't get your point of view about deleting the line. First, you must detect where you are coming from (API or not). Then delete the line.
Why fix a problem that you can prevent ?

On the other point, it could improve the performance of the UI, because concurrent requests are not blocking each other for a session lock, even if you are not using it.

**Comment by jjanvier** [comment]
> Imagine 10000 per hour of the API, creating 1000000 lines in 5 days for... nothing.
OK, I understand now.

You don't prevent the problem as you don't do it globally. The problem will re appear the next time we'll do something related (even far related) to the session. IMO, you can't assume that every developer coming in the team will be aware of this problem and will correctly check the session. This is something too tricky, and far hidden in the code stack.

**Pull request closed without merging**
