### PR TITLE
fix mistakenly passed route parameter

### LINKED ISSUE #6414: Delete button generates an error
**I'm reporting a Bug**

When creating a new import or export profile, and after setting the 3 requested values in the popup. On the first edit screen that you see and before saving anything there is also a "delete" button. Pressing it generates an error 404 in the console.

Probably because the new resource has not been created, maybe the delete button should just dissappear from that screen in that situation.

### PR DESCRIPTION
**Pull request by latenzio**
fixes #6414

### CODE REVIEW

**Comment by grena** [comment]
Hello @latenzio , thank you for your contribution! :)
I see you already signed our Akeneo Contributor Agreement, so that's perfect.

Here are the next steps before we merge this contribution:
- [ ] I'll write a test to cover this case to ensure no more regression & I'll fill in the Changelog file
- [ ] We'll run this PR on our continuous integration tool to run the test suite
- [ ] You'll need 2 GTM from the core team

**Comment by latenzio** [comment]
@grena i added some tests, squashed and rebased this PR on latest commit of branch `1.7`

**Comment by grena** [comment]
Hello @latenzio , I added a behat test and a note in the Changelog.
Here is the new PR https://github.com/akeneo/pim-community-dev/pull/7123. 
Once validated by the core team and green on our CI tool, we'll merge!

**Comment by grena** [comment]
Your fix has been merged (https://github.com/akeneo/pim-community-dev/pull/7123) and the fix is now available in the 1.7.13 patch. Thanks again for your contribution!

**Pull request closed without merging**
