### PR TITLE
PIM-5450: require correct version of mongo db bundle

### PR DESCRIPTION
**Pull request by jmleroux**
| Q                 | A
| ----------------- | ---
| Specs             |not needed
| Behats            |not needed
| Blue CI           |runnin
| Changelog updated |not needed
| Review and 2 GTM  |

### CODE REVIEW

**Comment by jmleroux** [comment]
This PR is linked to #3874 : we still need to ad the mongo requirement, but we must not bump the version in 1.4

**Comment by jjanvier** [comment]
gtm

**Comment by solivier** [comment]
gtm

**Comment by jmleroux** [comment]
Not GTM for now

**Pull request merged**
