### PR TITLE
PIM-5271: Remove OroLocaleBundle

### PR DESCRIPTION
**Pull request by skeleton**
| Q                 | A
| ----------------- | ---
| Specs             | N
| Behats            | N
| Blue CI           | ?
| Changelog updated | TODO
| Review and 2 GTM  | N
| Micro Demo (PO)   | N
| Migration script  | N
| Tech Doc          | N

### CODE REVIEW

**Comment by nidup** [comment]
much :heart: GTM

**Comment by nidup** [comment]
i will update the upgrade.md once merged if you want (anyway we'll need to explain a bit the localization component + bundle in this file before the release)

**Comment by pierallard** [comment]
GTM (just need Travis to be OK and 1 little remark). Nice job, impressed to have blue CI with 10.000 removed lines without changing many behats.

**Comment by nidup** [comment]
I re-read new commits since my first review and i pulled it on my dev to play with, GTM and congrats!

**Pull request merged**
