### PR TITLE
Fix a failing scenario

### PR DESCRIPTION
**Pull request by ClementGautier**
| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | N/A
| Added Behats                      | N/A
| Changelog updated                 | N/A
| Review and 2 GTM                  | todo
| Micro Demo to the PO (Story only) | N/A
| Migration script                  | N/A
| Tech Doc                          | N/A

### CODE REVIEW

**Comment by jjanvier** [comment]
gtm

**Comment by phaseinducer** [comment]
GTM

**Comment by pierallard** [comment]
:jetpack:
gtm

**Comment by jjanvier** [comment]
I have faith in you @ClementGautier :pray:

**Comment by nidup** [comment]
GTM, thanks! :wolf: stateful versioning :wolf:

**Pull request closed without merging**
