### PR TITLE
Improve the context map (squad point of vue) to make it clearer

### PR DESCRIPTION
**Pull request by arnolanglade**
**Description (for Contributor and Core Developer)**

**Before:**
old-all-team

**After:**

All teams

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | -
| Added legacy Behats               | -
| Added acceptance tests            | -
| Added integration tests           | -
| Changelog updated                 | -
| Review and 2 GTM                  | Todo
| Micro Demo to the PO (Story only) | -
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

### CODE REVIEW

**Comment by jjanvier** [comment]
there is no diff between your images oO

**Comment by fitn** [comment]
The direction of the arrows are differents

**Comment by arnolanglade** [comment]
Yes the PM did not understand this sketch :)

**Comment by jjanvier** [comment]
this is clearer imo :+1:

**Pull request merged**
