### PR TITLE
Fix for #12049 - null pointer exception on Product::getVariationLevel

### PR DESCRIPTION
**Pull request by shavounet**
**Description (for Contributor and Core Developer)**

See #12049 for bug description. It's mostly triggered by custom code, but some services fail where they shouldn't due to an unexpected error.

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | Todo
| Added legacy Behats               | Todo
| Added acceptance tests            | Todo
| Added integration tests           | Todo
| Changelog updated                 | Todo
| Review and 2 GTM                  | Todo
| Micro Demo to the PO (Story only) | Todo
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

### CODE REVIEW

**Comment by nestorAkeneo** [comment]
:heart_eyes: Thanks for taking the time to contribute! You're awesome! :heart_eyes:

In order for your contribution to benefit all other contributors and users, we need your permission.

For that, it is enough that you read this document, and that you sign it, if it suits you.

[Contributor Agreement](http://www.akeneo.com/contributor-license-agreement/)

**Comment by jmleroux** [comment]
CLA check

**Review by juliensnz — APPROVED** [review]

**Review by nmarniesse — APPROVED** [review]

**Comment by shavounet** [comment]
Hi ! Any news about this PR ? I see 2 pending CI job, is there any thing I can do ?

**Comment by jmleroux** [comment]
We merged this PR in another one by cherry picking your contribution in order to run the CI.

Thanks a lot again!

:pray:

**Pull request closed without merging**
