### PR TITLE
disable Xdebug to speed up builds

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by xabbuh** [comment]
Looks like the Travis build without Xdebug enabled takes approximately half the time of what it used before.

**Comment by jmleroux** [comment]
Totally agree, i was testing the same thing in #3888 
Thanks for this PR, I need to check if you already signed the contributor agreement before giving my GTM.

**Comment by nidup** [comment]
GTM

**Comment by jmleroux** [comment]
PR merged, now our 1.4 Travis builds will be faster.
Thanks a lot.

**Comment by xabbuh** [comment]
You're welcome. :)

**Pull request merged**
