### PR TITLE
PIM-3690 : change group selection with select2

### PR DESCRIPTION
**Pull request by grena**
| Q                    | A
| -------------------- | ---
| Bug fix?             | N
| New feature?         | N
| BC breaks?           | N
| CI currently passes? |
| Tests pass?          | Y
| Scenarios pass?      |
| Checkstyle issues?*  | N
| PMD issues?**        | N
| Changelog updated?   | N
| Fixed tickets        | PIM-3690
| DB schema updated?   | N
| Migration script?    | N
| Doc PR               | N

### CODE REVIEW

**Comment by sumbobyboys** [comment]
GTM, hopefully

**Comment by nidup** [comment]
GTM

**Comment by grena** [comment]
Oh wait ! I'm adding something ! :)

**Comment by grena** [comment]
Ok that's it, I'm GTM

**Pull request merged**
