### PR TITLE
Add more informations in batch logs

### PR DESCRIPTION
**Pull request by fitn**
Add more informations in batch logs to help integrators to debug

| Q | A |
| --- | --- |
| Added Specs | N |
| Added Behats | N |
| Changelog updated | N |
| Review and 2 GTM | Waiting |
| Micro Demo to the PO (Story only) | N |
| Migration script | N |
|  Tech Doc | N |

### CODE REVIEW

**Comment by jjanvier** [comment]
Gtm

**Comment by nidup** [comment]
GTM

**Comment by grena** [comment]
@fitn is this PR still relevant?

**Comment by fitn** [comment]
Yes still ;)

**Comment by ahocquard** [comment]
@fitn is is still relevant? Will you merge it soon?

This branch is the oldest one on the PIM :smile:

**Comment by fitn** [comment]
It is still relevant. Anyway, as it won't be merged, I close the PR and delete the branch.

**Pull request closed without merging**
