### PR TITLE
PIM-5926: When I go back in mass-classify products, I return to the mass-edit attributes

### PR DESCRIPTION
**Pull request by loicguillois**
**Description**

Fix the back button behaviour on mass-classify second step (configure)

**Definition Of Done**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | N
| Added Behats                      | Y
| Changelog updated                 | N
| Review and 2 GTM                  | Y
| Micro Demo to the PO (Story only) | N
| Migration script                  | N
| Tech Doc                          | Y

### CODE REVIEW

**Comment by jjanvier** [comment]
gtm

**Comment by jjanvier** [comment]
no need to update the changelog? it's only a "master" bug?

**Comment by willy-ahva** [comment]
GTM

**Comment by willy-ahva** [comment]
But maybe it needs a little behat ?

**Comment by loicguillois** [comment]
@jjanvier: these screens were not present in previous versions

@willy-ahva: I will check that

**Comment by damien-carcel** [comment]
And maybe not juste one behat: as you work in the AbstractController, it impacts all the mass edit.
GTM once tested.

**Comment by loicguillois** [comment]
Added some Behat and updated the documentation too: https://akeneo.atlassian.net/wiki/display/AKN/Installing+and+using+behat

**Pull request merged**
