### PR TITLE
[RFC] Add align equals to php_cs

### PR DESCRIPTION
**Pull request by juliensnz**
We vote on this PR 👍  or 👎 

Today we align the arrays:
```
$array = [
    'such' => 'align',
    'much' => 'nice'
]
```

but we don't align assignations:

```
$advice = 'you should vote for this pr';
$because = 'it will save penguins';
$and = 'penguins are really nice and funny'
```

### CODE REVIEW

**Comment by juliensnz** [comment]
👍

**Comment by ClementGautier** [comment]
:-1: IMO it creates useless diff lines and unecessary effort. BTW it is not the coding standard used by project like symfony/symfony and I think there is good reason for that.

**Comment by shadypierre** [comment]
👍

**Comment by ToonMolo** [comment]
👍

**Comment by jmleroux** [comment]
:-1:

**Comment by jjanvier** [comment]
I'd vote to simply remove all the rules and stick to PSR-2 or Symfony
That makes easier to switch between projects

**Comment by juliensnz** [comment]
@jjanvier ok, so I will not add a blank line before the namespace, not order uses and put the phpdoc in random order :)

**Comment by jjanvier** [comment]
@juliensnz 
> ok, so I will not add a blank line before the namespace
I will definitely not sleep anymore 
> not order uses 
same
> and put the phpdoc in random order 
agree this one sucks
> and never use simple quotes
I won't sleep with this one neither...
> . And we will also have to always do phpdoc long descriptions, 
same
> concat without spaces, etc.
same

But I think you missunderstood my point. I'm not against using Symfony CS. If the team wants it, great. I just want to use a standard in every project (symfony or PSR2, personally I don't care). I don't want any custom rule that's all.

Stricly PSR2 or strictly Symfony, that's all I ask.

**Comment by jmleroux** [comment]
Anyway, it seems settled. This PR should be closed.

**Comment by a2xchip** [comment]
UX > then UI! No unneeded aligns! PHP Fig standards enaugh :-)

**Pull request closed without merging**
