### PR TITLE
TIP-1392: Move 3.2 to 4.0 migration script in a dedicated folder

### PR DESCRIPTION
**Pull request by pierrejolly**
**Description (for Contributor and Core Developer)**

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | -
| Added legacy Behats               | -
| Added acceptance tests            | -
| Added integration tests           | -
| Changelog updated                 | -
| Review and 2 GTM                  | Todo
| Micro Demo to the PO (Story only) | -
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

### CODE REVIEW

**Comment by ahocquard** [comment]
@jjanvier should we not purge the database to avoid warning? The directory and the database will nt be up to date. You can define several directories as in the documentation (https://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html), but it's defined by namespace :/

**Comment by jjanvier** [comment]
@ahocquard 

> should we not purge the database to avoid warning

I don't understand what you mean. AFAIK, this will work.

**Comment by ahocquard** [comment]
Seen IRL with JJ, it can be a problem because the filename is still in database. It will generate a ton of warnings for nothing.

**Comment by jjanvier** [comment]
If we merge that, the nightly step `deploy_upgrade_pim3_environment` won't work. Closing.

**Pull request closed without merging**
