### PR TITLE
Fixes error in TranslateFlashMessagesSubscriber when Session is not started

### PR DESCRIPTION
**Pull request by vpetrovych**
| Q                    | A
| -------------------- | ---
| Bug fix?             | Y
| New feature?         | N
| BC breaks?           | N
| CI currently passes? |
| Tests pass?          | 
| Scenarios pass?      |
| Checkstyle issues?*  |
| PMD issues?**        |
| Changelog updated?   |
| Fixed tickets        |
| DB schema updated?   |
| Migration script?    |
| Doc PR               |

### CODE REVIEW

**Comment by vpetrovych** [comment]
Fixes #2912

**Comment by phaseinducer** [comment]
Hi, thanks for your PR !

Could you please also sign the agreement as stated in contributing.md ? http://www.akeneo.com/contributor-license-agreement/

**Comment by vpetrovych** [comment]
@phaseinducer Hey, I did sign it.

**Comment by phaseinducer** [comment]
Oh right, my mistake !
I merge your fix, so it will appear in 1.4. Thanks again for your contribution. ; )

**Pull request merged**
