### PR TITLE
Need to escape backslash

### PR DESCRIPTION
**Pull request by smalot**
[//]: <> (<3 Thanks for taking the time to contribute! You're awesome! <3)

[//]: <> (If you've never contributed to this repository before, please read https://github.com/akeneo/pim-community-dev/blob/master/.github/CONTRIBUTING.md)

**Description (for Contributor and Core Developer)**

The current shcema upgrade is not applied due to malformed sql query.
Backslash need to be escaped in the query.

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | -
| Added Behats                      | -
| Added integration tests           | -
| Changelog updated                 | Todo
| Review and 2 GTM                  | -
| Micro Demo to the PO (Story only) | -
| Migration script                  | OK
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

### CODE REVIEW

**Comment by jjanvier** [comment]
Thank you very much for your contribution Sebastien!

**Comment by pierallard** [comment]
Hi @smalot ! Thanks for your contribution ;)
Before merging your PR, we need you to accept the contributor agreement, available here
https://www.akeneo.com/contributor-license-agreement/

Thanks again !

**Comment by smalot** [comment]
Done

**Comment by pierallard** [comment]
Thanks for your PR @smalot  ! Merged ;)

**Comment by a2xchip** [comment]
Ta-daaa!!!

**Comment by smalot** [comment]
Merci

**Pull request merged**
