### PR TITLE
Fix migration script 1.4 to 1.5

### PR DESCRIPTION
**Pull request by willy-ahva**
| Q                                 | A
| --------------------------------- | ---
| Added Specs                       |
| Added Behats                      |
| Changelog updated                 |
| Review and 2 GTM                  |
| Micro Demo to the PO (Story only) |
| Migration script                  |
| Tech Doc                          |
```

### CODE REVIEW

**Comment by juliensnz** [comment]
GTM

**Comment by phaseinducer** [comment]
GTM

**Comment by skeleton** [comment]
gtm

**Comment by grena** [comment]
gtm

**Pull request merged**
