### PR TITLE
Search inside attribute options

### PR DESCRIPTION
**Pull request by Hocdoc**
Our users want to search attribute options *inside* attribute option labels.

This worked already in the filters for the product grid, but inside the PEF the user can just search at the beginning of the attribute option labels.

### CODE REVIEW

**Comment by jjanvier** [comment]
GTM

**Comment by juliensnz** [comment]
GTM

**Comment by juliensnz** [comment]
Hello @Hocdoc,

Good news, we are currently running this PR on our ci. I will keep you updated on this subject, but this contribution may be merged one day :)

Thanks a lot again for this contribution.

Regards,

Julien

**Comment by pierallard** [comment]
Hi Hodcoc ! The CI results are all green! I merge your contribution.
Thanks a lot for it !!! :tada:

Pierre

**Pull request merged**
