### PR TITLE
Partially revert 1b22956abf7bb8b79b5e24510f6824c7a83938b3.

### PR DESCRIPTION
**Pull request by yunosh**
**Description (for Contributor and Core Developer)**

This looks like incorrectly resolved merge conflict, which added back the hardcoded template into the, then master, now 1.7, branch, where the templates had been  outsourced earlier.

### CODE REVIEW

**Comment by yunosh** [comment]
This has to be merged to all branches up to master.

**Comment by damien-carcel** [comment]
Hello @yunosh.

Thank you for this contribution. I just put it to review by our core-team, this one and https://github.com/akeneo/pim-community-dev/pull/7179 too.

For us to be able to merge your contribution, we also need that you sign our contributor license aggreement (30 seconds to fill it :wink:).

Regards,
Damien.

**Comment by damien-carcel** [comment]
Pull request merged. Thank you so much for the contribution @yunosh

**Comment by yunosh** [comment]
Has this been merged to later branches too?

**Pull request merged**
