### PR TITLE
API-1467: Replace mass edit legacy behat test by end to end

### PR DESCRIPTION
**Pull request by willy-ahva**
**Description (for Contributor and Core Developer)**

It removes 13 scenarios from the following files:
- tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes_scopable_localizable.feature
- tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes_product_model.feature
- tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes.feature
- tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/add_attribute_value.feature
- tests/legacy/features/pim/enrichment/product/mass-edit/classify_product_model.feature
- tests/legacy/features/pim/enrichment/product/mass-edit/change_status.feature

They are all handled by the following files:
- tests/back/Pim/Enrichment/EndToEnd/Product/MassEdit/MassEditAttributeValueOfEntitiesEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/MassEdit/MassEditCategoriesOfEntitiesEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/MassEdit/MassEditStatusOfEntitiesEndToEnd.php

The add an attribute, add a category, remove a category, move to category mass edit actions are not covered by legacy behat anymore but all the others are still covered.

The edit common attribute action is covered with 1 scenario by type of attribute (edit text, edit the image, edit simple select, etc.). Should I remove all the scenarios to keep only 1 that covered the edit common attribute for a text?

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | -
| Added legacy Behats               | -
| Added acceptance tests            | -
| Added integration tests           | -
| Changelog updated                 | -
| Review and 2 GTM                  | Todo
| Micro Demo to the PO (Story only) | Todo
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

### CODE REVIEW

**Comment by tseho** [comment]
No :fire: in 5.0 :(

**Review by tseho — APPROVED** [review]

**Review by pierrejolly — APPROVED** [review]

**Comment by tseho** [comment]
Can we abandon this one ?

**Comment by willy-ahva** [comment]
> Can we abandon this one ?

Maybe we should try to merge it ?

**Comment by tseho** [comment]
> Maybe we should try to merge it ?

Sure, if you have the time, you can rebase and check the CI.

**Pull request closed without merging**
