### PR TITLE
Api 1341 - Updated API error output format

### PR DESCRIPTION
**Pull request by RiffVentura**
**Description (for Contributor and Core Developer)**
API concatenates error messages together without leaving a space character in between
This pull request threats only errors done by search filters validation for the following endpoints:
- family (is already fixed on master)
- category
- attribute
- attributeGroup

~~Updated namespaces from DateTime to DateTimeInterface as the former was removed since PHP 7.2~~

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | -
| Added legacy Behats               | -
| Added acceptance tests            | -
| Added integration tests           | -
| Changelog updated                 | -
| Review and 2 GTM                  | Todo
| Micro Demo to the PO (Story only) | -
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

### CODE REVIEW

**Review by pchasle — APPROVED** [review]
:ok_hand:
You might have some tests to update

**Comment by tseho** [comment]
> Updated namespaces from DateTime to DateTimeInterface as the former was removed since PHP 7.2
Can you elaborate ?

I'm not aware of `\DateTime` or  `\DateTimeInterface` to be removed from PHP.

**Comment by RiffVentura** [comment]
> > Updated namespaces from DateTime to DateTimeInterface as the former was removed since PHP 7.2
> 
> Can you elaborate ?
> 
> I'm not aware of `\DateTime` or `\DateTimeInterface` to be removed from PHP.

My bad, I meant DateTime constants
Look at the changelog here:
https://www.php.net/manual/en/class.datetime.php
Basically constants are moved from DateTime to DateTimeInterface

**Review by tomglvng — APPROVED** [review]

**Comment by tseho** [comment]
I edited my message:
> Ok, you are talking about the constants. And that's not correct, those constants were not removed, they were moved from the class to the interface but does not change anything because DateTime extends DateTimeInterface.
So, IMHO, this is an unnecessary change since both versions are valid.

**Comment by RiffVentura** [comment]
> So, IMHO, this is an unnecessary change since both versions are valid.

I thought it can be dangerous to leave it be, since it can be removed later at any point
Do you want to me to revert it ?

**Comment by tseho** [comment]
> I thought it can be dangerous to leave it be, since it can be removed later at any point
This is not a deprecation, they removed nothing, they just moved constants from a class to its interface.
They will not remove it, it's not dangerous.

**Comment by tseho** [comment]
> Do you want to me to revert it ?

Would be better, I honestly think it was unnecessary.

**Review by tseho — APPROVED** [review]

**Pull request merged**
