### PR TITLE
[TR] PIM-5386: Association tabs are displayed one by one in PEF

### PR DESCRIPTION
**Pull request by willy-ahva**
| Q                 | A
| ----------------- | ---
| Specs             | ok
| Behats            | ok
| Blue CI           |  ok
| Changelog updated | no need
| Review and 2 GTM  | ok
| Micro Demo (PO)   |
| Migration script  |
| Tech Doc          |

### CODE REVIEW

**Comment by skeleton** [comment]
gtm

**Comment by grena** [comment]
GTM

**Comment by grena** [comment]
GTM

**Comment by skeleton** [comment]
gtm

**Comment by phaseinducer** [comment]
GTM

**Pull request merged**
