### PR TITLE
Fix undefined $parametersViolations

### PR DESCRIPTION
**Pull request by aistis-**
**Description (for Contributor and Core Developer)**

Bugfix for undefined `$parametersViolations`! If there is not raw parameters defined for the job - it will fail.

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | -
| Added Behats                      | -
| Added integration tests           | -
| Changelog updated                 | Ok
| Review and 2 GTM                  | Ok
| Micro Demo to the PO (Story only) | -
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

### CODE REVIEW

**Comment by aistis-** [comment]
Any update?

**Comment by SamirBoulil** [comment]
Hello @aistis- !

Thank you for your bug fix! I'll have it reviewed by the team and run the CI on it.

I'll keep you updated on this PR status.

**Comment by aistis-** [comment]
Thanks for the update! I guess, the whole controller needs to be cleaned, but at least it fixes the undefined variable :)

**Comment by SamirBoulil** [comment]
Hello @aistis- !

Great news ! We are all set for merging regarding the code.

The only last thing we need is that you read and sign the contributor agreement http://www.akeneo.com/contributor-license-agreement if that's fine with you.

**Comment by aistis-** [comment]
@SamirBoulil signed. First time I see such a thing in open source :)

**Comment by a2xchip** [comment]
It is because of specific os licence

**Comment by SamirBoulil** [comment]
Congratulations @aistis- , Your PR has been merged !

🎉  Again, thank you for your contribution ! 

You can now claim your badge "Core contributor" on http://badger.akeneo.com if you don't already have it. ^^

If you wish to contribute again, don't hesitate to look at our github project board where we labeled all kinds of tasks to take on ! https://github.com/akeneo/pim-community-dev/projects/1

**Pull request merged**
