### PR TITLE
PIM-10277-refuse-disabled-users

### PR DESCRIPTION
**Pull request by FSAkeneo**
**Description (for Contributor and Core Developer)**

Preventing disabled users to enter the PIM.

Proposition without UserChecker, to be like the coupled PR on EE (not called by SAML Bundle, see jira ticket).
Coupled with PR on EE with same name : https://github.com/akeneo/pim-enterprise-dev/pull/12973

**Definition Of Done (for Core Developer only)**

- [ ] Tests
- [ ] Migration & Installer
- [ ] PM Validation (Story)
- [ ] Changelog (maintenance bug fixes)
- [ ] Tech Doc

### CODE REVIEW

**Comment by RiffVentura** [comment]
You should update [user provider specs](https://github.com/akeneo/pim-community-dev/blob/master/tests/back/UserManagement/Specification/Bundle/Security/UserProviderSpec.php) and delete Custom user checker specs :wink:

**Comment by FSAkeneo** [comment]
I'll manage to remove the useless specs and are tests for the fix.

**Review by RiffVentura — APPROVED** [review]

**Review by StevenVAIDIE — APPROVED** [review]
Do not forget to change the CHANGELOG.md

**Review by StevenVAIDIE — COMMENTED** [review]
Did you check with the API ?

**Comment by FSAkeneo** [comment]
> Did you check with the API ?

I've not test that before, can you give me a hand tomorrow ?

**Review by amigaire — APPROVED** [review]

**Comment by FSAkeneo** [comment]
Ok, checked and fixed with @StevenVAIDIE, it needed something to prevent disabled users to obtain a token for api calls.

**Pull request merged**
