### PR TITLE
CXP-785: add skeleton

### PR DESCRIPTION
**Pull request by willy-ahva**
**Description (for Contributor and Core Developer)**
skeleton

**Definition Of Done (for Core Developer only)**

- [ ] Tests
- [ ] Migration & Installer
- [ ] PM Validation (Story)
- [ ] Changelog (maintenance bug fixes)
- [ ] Tech Doc

### CODE REVIEW

**Review by tseho — APPROVED** [review]

**Review by romaindak — APPROVED** [review]

**Comment by RiffVentura** [comment]
Shouldn't skeletons of helper, extensions list and app list  be independent ? 
Extensions list and app list are fetched via two different endpoint calls, so helper skeleton should be there until both calls respond
IMO we should have two skeleton components : one for helper, one for a list (we can then reuse it on apps later)

**Comment by tseho** [comment]
> Shouldn't skeletons of helper, extensions list and app list be independent ?
Are we not waiting for the response of both endpoints before displaying the content ?

**Comment by RiffVentura** [comment]
> > Shouldn't skeletons of helper, extensions list and app list be independent ?
> 
> Are we not waiting for the response of both endpoints before displaying the content ?

I was not aware that it was the end goal. Nevermind :)

**Comment by tseho** [comment]
> I was not aware that it was the end goal. Nevermind :)

This is easier, especially for the helper part where we add both counts.

**Pull request merged**
