### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by wakqasahmed**

### CODE REVIEW

**Comment by nidup** [comment]
Hi @wakqasahmed 

Good catch, thank you for fixing this typo!

Could you please read and sign our contributor agreement https://www.akeneo.com/contributor-license-agreement/, I need it to merge this pull request on the community dev repository.

Thank you!

**Comment by nidup** [comment]
Hi @wakqasahmed

Any news for the contributor agreement?

Have a good day!

**Comment by wakqasahmed** [comment]
@nidup done :)

**Comment by nidup** [comment]
@wakqasahmed thank you :)

**Pull request merged**
