### PR TITLE
[TR] PIM-5021: Forbid the use of code 'category' for an attribute

### PR DESCRIPTION
**Pull request by pierallard**
| Q                 | A
| ----------------- | ---
| Specs             | y
| Behats            | y
| Blue CI           | TODO
| Changelog updated | n
| Review and 2 GTM  | n

* The CHANGELOG needs to be updated or not ? *

### CODE REVIEW

**Comment by solivier** [comment]
no behats ?

**Comment by grena** [comment]
GTM, but how does it behave with an existing attribute with this code? It could raise save problems no?

**Comment by solivier** [comment]
GTM

**Comment by pierallard** [comment]
@grena When an attribute is called "category", the grid is not loaded. So I think this can even be doable.

**Comment by grena** [comment]
Ok then, thanks for your answer!

**Pull request merged**
