### PR TITLE
TIP-860: Add a class parameter for file controller storages

### PR DESCRIPTION
**Pull request by anaelChardan**
**Description (for Contributor and Core Developer)**

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | Todo
| Added legacy Behats               | Todo
| Added acceptance tests            | Todo
| Added integration tests           | Todo
| Changelog updated                 | Todo
| Review and 2 GTM                  | Todo
| Micro Demo to the PO (Story only) | Todo
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

### CODE REVIEW

**Comment by anaelChardan** [comment]
CI is good, ready to merge @jjanvier

**Comment by jjanvier** [comment]
You introduce this parameter to override it in EE?
I'm not sure this is the right solution.

Can't we instead duplicate the service in EE with the catalog storage you need?

What is this `pim_enrich.controller.file` about? What's its job?

**Comment by anaelChardan** [comment]
This controller is used at many places, with that we open to extension and it avoids to override the whole service

**Comment by anaelChardan** [comment]
The idea come from @arnolanglade

**Pull request closed without merging**
