### PR TITLE
PIM-9679: Clean line breaks in product and product model imports

### PR DESCRIPTION
**Pull request by nmarniesse**
**Description (for Contributor and Core Developer)**

https://akeneo.atlassian.net/browse/PIM-9679

During import we display a warning message when a value is fixed

Part1:
- [x] skip line break in product import and display message
- [x] skip line break in product model import and display message

Part2: Done in another PR

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | OK
| Added legacy Behats               | -
| Added acceptance tests            | -
| Added integration tests           | -
| Changelog updated                 | OK
| Review and 2 GTM                  | Todo
| Micro Demo to the PO (Story only) | -
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

### CODE REVIEW

**Review by mmetayer — APPROVED** [review]
Shouldn't we implement the same behavior for the API?

**Review by pchasle — APPROVED** [review]

**Review by pchasle — COMMENTED** [review]
Do you want to add a changelog in this PR or part2 only ?

**Comment by nmarniesse** [comment]
> Shouldn't we implement the same behavior for the API?

Maybe. I let the maintenance team decides, as the ticket is a SLA I merge this PR right now

**Comment by nmarniesse** [comment]
> Do you want to add a changelog in this PR or part2 only ?

The changelog is done in the part2 (already merged)

**Pull request merged**
