### PR TITLE
Enhance contributing doc to take DOD in account

### PR DESCRIPTION
**Pull request by nidup**
There is a proposal for a new contributing.md, we only discussed about story this morning so I splitted expectations about story and bug fix (we can merge in a single table if you want but it has some impacts on support and maintenance workflow).

### CODE REVIEW

**Comment by grena** [comment]
GTM

**Comment by phaseinducer** [comment]
GTM

**Comment by jjanvier** [comment]
by reading this, as an external contributor, I'd say whooooaaa, it's impossible to contribute

we should specify it's for core team, or even put it in CORE-TEAM-CONTRIBUTING.md

**Comment by ClementGautier** [comment]
@jjanvier putting it in CONTRIBUTING.md make it visible when you create a pull request on github, you have a link "Follow the contributing guideline".

I agree with @jjanvier that we have to specify how an external contributor can contribute, explain that jenkins build means behats and in parenthesis that core developpers can use jenkins for example.

**Comment by nidup** [comment]
ok i add a specific section for external contrib, thank you for the feedback!

**Pull request merged**
