### PR TITLE
CSV quick export job with all attributes not working

### PR DESCRIPTION
**Pull request by masmrlar**
| Q | A |
| --- | --- |
| Added Specs | N |
| Added Behats | N |
| Changelog updated | N |
| Review and 2 GTM | Y |
| Micro Demo to the PO (Story only) | N |
| Migration script | Y |
|  Tech Doc | N |

The quick export job with 'all attributes' from the product grid is not working as the job 'csv_product_quick_export' is missing.

The other quick export background jobs have been added in Version_1_6_201603100000_batch_jobs.php but not this one.

### CODE REVIEW

**Comment by jjanvier** [comment]
Hello @masmrlar,

Thank you for your contribution. It's really appreciated. Could you please rebase your commit and pull request on the 1.6 version please? Otherwise other contributors that migrate from 1.5 to 1.6 won't benefit from it.

But thanks again :)

**Comment by jjanvier** [comment]
GTM once fixed

**Comment by masmrlar** [comment]
I added a pull request for branch 1.6 - but i'm still checking the failing travis checks here...

**Comment by fabienlem** [comment]
Hello @masmrlar,

The travis failure is caused by the fact your class name doesn't match with the filename. Please let me know if you don't have time to fix this, in this case I will take care of this in order to merge the PR tomorrow.

Regards

**Comment by fabienlem** [comment]
Hello @masmrlar,

As you submitted a similar PR for the 1.6 branch, I'm closing this one. Fix which are not made on the master branches are applied on the others branch on our side.

Regards

**Pull request closed without merging**
