### PR TITLE
Clarify message about APCu requirement

### PR DESCRIPTION
**Pull request by pamil**
**Description (for Contributor and Core Developer)**

Suggesting PHP 5 is confusing :)

### CODE REVIEW

**Comment by nidup** [comment]
Hey @pamil !

Thank you for the pull request! :tada: 

Could you read and sign the following contributor agreement https://www.akeneo.com/fr/contributor-license-agreement/ ?

Thank you!

**Comment by pamil** [comment]
@nidup done! :)

**Comment by nidup** [comment]
Thank you @pamil !

**Comment by nidup** [comment]
By the way, you can claim the core contributor badge on badger :dancer: http://badger.akeneo.com/badge/41acec2c-649f-11e6-92dc-d60437e930cf

**Comment by pamil** [comment]
Badges, more badges, yaaaay! 🎉

**Pull request merged**
