### PR TITLE
issue 4494 Fix

### PR DESCRIPTION
**Pull request by julienanquetil**
**Description (for Contributor and Core Developer)**
 Issue #4994 fix 
Thanks @nidup !

### CODE REVIEW

**Comment by nidup** [comment]
Hi @julienanquetil !

Thank you for the pull request :tada: 

Could you do it on 1.6 branch and not on master branch please? (you can pull 1.6, create a branch and cherry pick this commit).

Thank you!

**Comment by julienanquetil** [comment]
OH sh...  I update it, i hope it's better now..
Thanks

**Comment by nidup** [comment]
And one more fix! Thank you @julienanquetil you're on fire! :fire:

FYI, I cherry picked your commits here https://github.com/akeneo/pim-community-dev/pull/5029 before to merged because I had issue with our travisci

**Comment by julienanquetil** [comment]
Thanks, sorry for the branch error.... but it's done :)

**Pull request closed without merging**
