### PR TITLE
[WIP] GITHUB-5365: Remove useless option form PEF associations filters

### PR DESCRIPTION
**Pull request by a2xchip**
[//]: <> (<3 Thanks for taking the time to contribute! You're awesome! <3)

[//]: <> (If you've never contributed to this repository before, please read https://github.com/akeneo/pim-community-dev/blob/master/.github/CONTRIBUTING.md) 

**Description (for Contributor and Core Developer)**

See #5365 

[//]: <> (What does this Pull Request do? reference the related issue?)

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | :negative_squared_cross_mark: 
| Added Behats                      | :negative_squared_cross_mark:
| Changelog updated                 | :white_check_mark:
| Review and 2 GTM                  | :clock1:
| Micro Demo to the PO (Story only) | :negative_squared_cross_mark:
| Migration script                  | :negative_squared_cross_mark:
| Tech Doc                          | :negative_squared_cross_mark:

:white_check_mark: Done and pass

:red_circle: Done but fail

:clock1: Done but pending

:negative_squared_cross_mark: Not needed

### CODE REVIEW

**Comment by nidup** [comment]
This filter should not be displayed but it's used to apply permissions on enterprise edition, only display product you have the permission to view or edit (permissions are defined per user groups for categories)

**Comment by a2xchip** [comment]
@nidup Not displayed like ```display: none;```?

**Comment by nidup** [comment]
yes, we don't have the issue on the main product grid as in fact the category filter is always displayed (in the left panel of categories)

**Comment by a2xchip** [comment]
@nidup EE test is green :( Could you explain me more how to check the problem, or how to provide test coverage for it?

**Comment by nidup** [comment]
For instance, in EE, define that Julia has no view permission on a category catA, if a product is only classified in the catA, Julia should not see the product in product grid neither in product association grid. As permissions are applied in grid through this filter, I guess that with the fix you propose Julia will see the product in the product association grid (even if the product is classified in catA).

**Pull request closed without merging**
