### PR TITLE
PIM-4537: Add a new counter "read_lines" + translation in our new CSV Reader

### PR DESCRIPTION
**Pull request by solivier**
| Q                    | A
| -------------------- | ---
| Bug fix?             | No
| New feature?         | No
| BC breaks?           | No
| CI currently passes? | Yes
| Tests pass?          | Yes
| Scenarios pass?      | Yes
| Checkstyle issues?*  | No
| PMD issues?**        | No
| Changelog updated?   | No
| Fixed tickets        | PIM-4537
| DB schema updated?   | No
| Migration script?    | No
| Doc PR               | No

Build: http://core-ci.akeneo.com/job/pim-pr-behat/2797

### CODE REVIEW

**Comment by willy-ahva** [comment]
GTM

**Comment by phaseinducer** [comment]
Capitalization is not consistent between translation files and behats

**Comment by solivier** [comment]
it's on other keys I didn't touch them

**Comment by phaseinducer** [comment]
So maybe it's the right time to clean it. ; )

**Comment by nidup** [comment]
GTM if CI ok

**Pull request merged**
