### PR TITLE
[SLA] PIM-5727: Fix permission issue on add-attribute extension on edit common attributes step

### PR DESCRIPTION
**Pull request by pierallard**
<3 Thanks for taking the time to contribute! You're awesome! <3

Thank you, that's my job

**Description (for Contributor and Core Developer)**

When a user have no rights to "add attribute" on a product form, the "add-attribute" form extension is not loaded on the "Edit common attributes" step, event if he have permission.

The solution is to remove the permission check because this form extension should always be loaded (seen with PO's).

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | n
| Added Behats                      | y
| Changelog updated                 | n
| Review and 2 GTM                  | n
| Micro Demo to the PO (Story only) | n
| Migration script                  | n
| Tech Doc                          | n

### CODE REVIEW

**Comment by juliensnz** [comment]
GTM

**Comment by solivier** [comment]
gtm

**Comment by grena** [comment]
GTM

**Comment by pierallard** [comment]
Merged in https://github.com/akeneo/pim-community-dev/pull/4410

**Pull request closed without merging**
