### PR TITLE
Fixed issue with pim-popinform js code

### PR DESCRIPTION
**Pull request by dimitri-koenig**
This PR fixes an issue with popinform js widget, which has some bugs if used multiple times on the same page.

### CODE REVIEW

**Comment by phaseinducer** [comment]
Hello Dimitri,

Thanks for the fix! It looks good to me. I will run our continuous integration tests on your PR, then if all is ok we'll merge.
Also could you please sign our [contributor license agreement](https://www.akeneo.com/contributor-license-agreement/)?

Best regards,
Yohan

**Comment by phaseinducer** [comment]
Hey Dimitri, sorry I just saw you already signed some time ago.
The CI is running ; )

**Comment by grena** [comment]
GTM

**Comment by phaseinducer** [comment]
Dimitri,

It seems that your branch is outdated, it causes composer dependencies conflicts with our current master. Can you rebase it on an up to date master branch?

Thanks!
Yohan

**Comment by dimitri-koenig** [comment]
Rebase done

**Comment by phaseinducer** [comment]
Ok, merged. I created a linked issue to keep a track in our changelog (#4879).
Thanks again, and feel free to write another contribution soon!
Oh, and we have a nice badges system for contributors, you can claim yours [here](http://badger.akeneo.com/badge/41acec2c-649f-11e6-92dc-d60437e930cf) if you want. ; )

**Comment by dimitri-koenig** [comment]
Wow, I'm impressed, that went fast. That's how you keep contributors happy :-)

**Pull request merged**
