### PR TITLE
Update jsmessages.it_IT.yml

### PR DESCRIPTION
**Pull request by comanche76**
Fix "Atributi" wrong translation.

**Description (for Contributor and Core Developer)**

**Definition Of Done (for Core Developer only)**

- [ ] Tests
- [ ] Migration & Installer
- [ ] PM Validation (Story)
- [ ] Changelog (maintenance bug fixes)
- [ ] Tech Doc

### CODE REVIEW

**Comment by nestorAkeneo** [comment]
:heart_eyes: Thanks for taking the time to contribute! You're awesome! :heart_eyes:

In order for your contribution to benefit all other contributors and users, we need your permission.

For that, it is enough that you read this document, and that you sign it, if it suits you.

[Contributor Agreement](http://www.akeneo.com/contributor-license-agreement/)

**Comment by pierrejolly** [comment]
Hello @comanche76, thank you for your contribution

We don't manage the translation directly in this repository, you can find more information to contribute on translation here : https://help.akeneo.com/pim/serenity/articles/contribute-translations.html

**Comment by StevenVAIDIE** [comment]
Hello @comanche76,

Thank you for your contribution ! Unfortunately modifying a translation cannot be solved by Merge Request.

The only single source of truth is Crowdin for not English translation. You can suggest your translation here if you want : https://crowdin.com/translate/akeneo/1854/en-it#74438

If you don't want/don't have time i can made the suggestion in crowdin.

Thank a lot for your lynx eye

**Comment by StevenVAIDIE** [comment]
Fixed in crowdin

**Pull request closed without merging**
