### PR TITLE
Split variant group add products scenario

### PR DESCRIPTION
**Pull request by nidup**
Split the variant group scenario to multiple feature files to avoid issues with stateful versioning listener which is not reproducible with a classic use of the PIM (aka passing by the UI without updating x time the same product in the same process).

This versioning listener based on doctrine event is a real pack of :wolf: we plan to re-write the versioning using our storage events (first we need to always use saver/remover api, we're getting closer)

### CODE REVIEW

**Comment by solivier** [comment]
gtm

**Comment by pierallard** [comment]
Are you sure it works even if the features runs on the same worker?

**Comment by nidup** [comment]
Would say yes because it's an issue with the stateful versioning in the behat context even with the same worker different processes will run the behat.

**Comment by pierallard** [comment]
So... Gtm, but you run the CI first :troll:

**Comment by nidup** [comment]
It passed several time for real ;)

**Pull request merged**
