### PR TITLE
RAC-427: Use new clean removed attribute job in command

### PR DESCRIPTION
**Pull request by ValentinMumble**
**Description (for Contributor and Core Developer)**

- Remove `CleanValuesOfRemovedAttributes` service
- When called with attribute codes, the `pim:product:clean-removed-attributes` command now launches the clean removed attribute job and displays a link to its execution in the process tracker

Without attribute codes (no changes here):
image

With attribute codes:
image

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | Todo
| Added legacy Behats               | Todo
| Added acceptance tests            | Todo
| Added integration tests           | Todo
| Changelog updated                 | Todo
| Review and 2 GTM                  | Todo
| Micro Demo to the PO (Story only) | Todo
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

### CODE REVIEW

**Review by juliensnz — APPROVED** [review]

**Comment by tseho** [comment]
You removed the count from the output ?

**Comment by ValentinMumble** [comment]
> You removed the count from the output ?

@tseho well yes, as the command only launches the job now

**Review by SamirBoulil — APPROVED** [review]

**Review by StevenVAIDIE — APPROVED** [review]
Agree with Quentin comment i think we should continue to asking to the user if he really want to clean N product and N product models. In the interface we give those information

**Comment by ValentinMumble** [comment]
> Agree with Quentin comment i think we should continue to asking to the user if he really want to clean N product and N product models. In the interface we give those information

@tseho @StevenVAIDIE added here https://github.com/akeneo/pim-community-dev/pull/13494/commits/e089282e5bf70b155108821af3c234a3dd9d9bbb

**Review by tseho — APPROVED** [review]

**Review by StevenVAIDIE — APPROVED** [review]

**Pull request merged**
