### PR TITLE
[CI] Improve spin method

### PR DESCRIPTION
**Pull request by phaseinducer**
The goal of this PR is :
- to add info about the last exception that occured inside the callable passed to the `spin()` method
- to avoid nested spinning (a spinned method that call another one, if the second fail, the first should stop immediately)

### CODE REVIEW

**Comment by jmleroux** [comment]
avoid nested spinning useless loop is a good catch :+1:

**Comment by sumbobyboys** [comment]
Really nice PR and good job. GTM for me

**Comment by jmleroux** [comment]
GTM

**Comment by solivier** [comment]
GTM

**Pull request merged**
