### PR TITLE
PIM-5266: Split browse attribute feature

### PR DESCRIPTION
**Pull request by juliensnz**
| Q                 | A
| ----------------- | ---
| Added Specs       | NA
| Added Behats      | NA
| Travis CI is ok   | ?
| Changelog updated | N

### CODE REVIEW

**Comment by grena** [comment]
GTM if behat ok!

**Comment by skeleton** [comment]
GTM

**Comment by solivier** [comment]
GTM if it works on ci

**Comment by ClementGautier** [comment]
GTM

**Comment by jmleroux** [comment]
I would be worthwhile to try to refactor the way we search and sort in the grid, don't you think ?

**Pull request closed without merging**
