### PR TITLE
use the new container infrastructure on Travis

### PR DESCRIPTION
**Pull request by joshk**
faster better stronger

more capacity

generally just awesome

### CODE REVIEW

**Comment by jmleroux** [comment]
Hello @joshk ,
Great idea !
However, we use 4 spaces for our yaml files indentations.
Could you correct this point before we can merge ?

Regards,

JM

**Comment by joshk** [comment]
Sorry about the change, although YAML is fairly flexible about indentation, 2 spaces is recommended (http://docs.saltstack.com/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html#indentation)

Are you sure it is necessary to change this?

**Comment by sumbobyboys** [comment]
@joshk Yep, all files in this project use 4 spaces. So consistency is more important than recommendation right now :)

**Comment by joshk** [comment]
Ok, it might be easier then for you to add `sudo: false` to your project if that is alright. In the middle of some bug hunts :)

**Comment by jmleroux** [comment]
:+1: we  will surely integrate it in future PRs.

Thanks !

**Pull request closed without merging**
