### PR TITLE
Fix migration

### PR DESCRIPTION
**Pull request by aRn0D**
| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | no 
| Added Behats                      | no 
| Changelog updated                 | no 
| Review and 2 GTM                  | yes
| Micro Demo to the PO (Story only) | no
| Migration script                  | yes
| Tech Doc                          | no

### CODE REVIEW

**Comment by jjanvier** [comment]
oh yeah nice catch
gtml

**Comment by aRn0D** [comment]
Thanks to @skeleton !

**Comment by damien-carcel** [comment]
GTM

**Comment by skeleton** [comment]
gtm :)

**Pull request merged**
