### PR TITLE
Fix paths of image attributes at pim_catalog_product_template

### PR DESCRIPTION
**Pull request by krafas**
**Description (for Contributor and Core Developer)**

[//]: <> (What does this Pull Request do? reference the related issue?)

Migrating from `v.1.6` to `v1.7` I've got error: `Property "image" expects a string as data, "array" given.`

Paths of `image` attributes must be fixed when migrating product templates to `v1.7`

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | -
| Added Behats                      | -
| Added integration tests           | -
| Changelog updated                 | -
| Review and 2 GTM                  | Todo
| Micro Demo to the PO (Story only) | -
| Migration script                  | -
| Tech Doc                          | -

### CODE REVIEW

**Comment by SamirBoulil** [comment]
Hello @krafas !

Thank you for your bug fix, I'll  try the migration myself this afternoon and keep you updated on this PR status.

Do you mind reading and signing the contribution agreement if that's fine with you? http://www.akeneo.com/contributor-license-agreement

**Comment by pierallard** [comment]
Hey @krafas ! Thanks a lot, again, for your contribution !

**Comment by mickaelandrieu** [comment]
Congratulations @krafas, Your PR has been merged !

🎉 Again, thank you for your contribution !

You can now claim your "Core contributor" badge on [Badger](http://badger.akeneo.com).

If you wish to contribute again, don't hesitate to look at our github [project board](https://github.com/akeneo/pim-community-dev/projects/1
) where we labeled all kinds of tasks to take on !

**Comment by a2xchip** [comment]
:tada: :tada: :tada: :tada: :tada: :tada:

**Pull request merged**
