### PR TITLE
Make the PIM installable with PHP7

### PR DESCRIPTION
**Pull request by jjanvier**
Installation of a small catalog, 5000 products:
```
time php app/console pim:installer:db -e prod  32.76s user 1.44s system 60% cpu 56.115 total
time php7.0 app/console pim:installer:db -e prod  15.95s user 1.30s system 46% cpu 37.050 total
time php app/console akeneo:batch:job csv_product_import -e prod  1153.08s user 28.00s system 85% cpu 22:58.98 total
time php7.0 app/console akeneo:batch:job csv_product_import -e prod  379.59s user 25.28s system 69% cpu 9:46.33 total
```

| Q                 | A
| ----------------- | ---
| Specs             | -
| Behats            | - 
| Blue CI           | Running
| Changelog updated |  -
| Review and 2 GTM  |
| Micro Demo (PO)   | -
| Migration script  | -
| Tech Doc          | -

### CODE REVIEW

**Comment by nidup** [comment]
GTM

**Comment by grena** [comment]
GTM, awesome perfs!

**Comment by pierallard** [comment]
GTM

**Comment by ClementGautier** [comment]
GTM

**Comment by SamirBoulil** [comment]
GTM

**Comment by BitOne** [comment]
GTM :heart:

**Pull request merged**
