### PR TITLE
[TR] Behat : fix unstable feature add_new_option_to_choice_attribute

### PR DESCRIPTION
**Pull request by jmleroux**
| Q                 | A
| ----------------- | ---
| Specs             |n/a
| Behats            |fixed
| Blue CI           |yes
| Changelog updated |n/a
| Review and 2 GTM  |

Fix an unstable feature on 1.4 branch

### CODE REVIEW

**Comment by phaseinducer** [comment]
GTM if the CI is ok : )

**Comment by skeleton** [comment]
GTM ;)

**Comment by willy-ahva** [comment]
GTM

**Comment by juliensnz** [comment]
GTM

**Pull request merged**
