### PR TITLE
[TR] PIM-5197: Improve products export memory usage (backport PIM-5127 into 1.3)

### PR DESCRIPTION
**Pull request by jjanvier**
Tested with 10K products. Memory stays stable at 88MB.

| Q                 | A
| ----------------- | ---
| Specs             | Y
| Behats            | -
| Blue CI           | running
| Changelog updated | Y
| Review and 2 GTM  |

### CODE REVIEW

**Comment by phaseinducer** [comment]
GTM

**Comment by skeleton** [comment]
GTM

**Comment by sumbobyboys** [comment]
GTM dude

**Comment by solivier** [comment]
GTM

**Comment by grena** [comment]
GTM

**Comment by nidup** [comment]
GTM, fyi, @phaseinducer will re-work this fix on master

**Pull request merged**
