### PR TITLE
Pull up 6.0 to master

### PR DESCRIPTION
**Pull request by micheltag**

### CODE REVIEW

**Comment by jmleroux** [comment]
CLA check

**Comment by jmleroux** [comment]
CLA check with comment

**Comment by jmleroux** [comment]
CLA check with comment

**Comment by jmleroux** [comment]
CLA check with comment

**Comment by jmleroux** [comment]
CLA check with comment

**Comment by jmleroux** [comment]
[CLA check with comment]

**Comment by nestorAkeneo** [comment]
:heart_eyes: Thanks for taking the time to contribute! You're awesome! :heart_eyes:

In order for your contribution to benefit all other contributors and users, we need your permission.

For that, it is enough that you read this document, and that you sign it, if it suits you.

[Contributor Agreement](http://www.akeneo.com/contributor-license-agreement/)

**Pull request closed without merging**
