### PR TITLE
Single storage

### PR DESCRIPTION
**Pull request by jjanvier**
| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | Y
| Added Behats                      | Y
| Added integration tests           | Oh Yes
| Changelog updated                 | Y
| Review and 2 GTM                  | hopefully Y
| Micro Demo to the PO (Story only) | Todo-
| Migration script                  | will be done by Anael :p
| Tech Doc                          | -

### CODE REVIEW

**Comment by pierallard** [comment]
There are some commits without ticket number, it should be cool to rename it, only if it's not so painful.

**Comment by jjanvier** [comment]
@pierallard I'm really sorry about that, but I won't take that risk ^^

**Comment by mickaelandrieu** [comment]
In all cases, this can't be merged *without* minimal additions in docs, for real this change is big!

**Comment by jjanvier** [comment]
@mickaelandrieu we have a dedicated story for that

doc is not part of this PR

**Pull request merged**
