### PR TITLE
PIM-6092: Fixed a last minute review that broke the functionality

### PR DESCRIPTION
**Pull request by ClementGautier**
# Note

A regression was introduced when merging the previous fix of PIM-6092. Actually it worked, it was tested, then came a review where I changed the code and reran the behats, but not tested the functional "by hand". Call it a "too confidant review commit" that break things. Anyway, here is the working one.

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | -
| Added Behats                      | Already done here : https://github.com/akeneo/pim-enterprise-dev/pull/2382
| Added integration tests           | -
| Changelog updated                 | :white_check_mark: https://github.com/akeneo/pim-community-dev/pull/5475
| Review and 2 GTM                  | Todo
| Micro Demo to the PO (Story only) | Todo
| Migration script                  | -
| Tech Doc                          | -

### CODE REVIEW

**Comment by juliensnz** [comment]
It means that a behat is missing. Please add it :)

**Comment by pierallard** [comment]
Behat is done in the EE https://github.com/akeneo/pim-enterprise-dev/pull/2453

**Comment by damien-carcel** [comment]
Why is it not possible to have a behat in CE too?

**Comment by pierallard** [comment]
@damien-carcel autocomplete is managed by an external library and we don't add any option with this library in CE.

**Pull request merged**
