### PR TITLE
[TR][PAM] PIM-4709: Add a switch locale/scope to assets grid

### PR DESCRIPTION
**Pull request by phaseinducer**
https://akeneo.atlassian.net/browse/PIM-4709

| Q                  | A
| ------------------ | ---
| Migration script?  | N
| Behats             | N
| Specs & Static     | Y
| Changelog updated  | N

This is a just a refactoring PR, business logic will be implemented and tested in PIM-4338

### CODE REVIEW

**Comment by nidup** [comment]
why in UIBundle? and not in EnrichBundle? (UIBundle is kindof legacy from oro platform)

**Comment by nidup** [comment]
baby comment then GTM

**Comment by phaseinducer** [comment]
Moved to Enrich ; )

**Comment by jjanvier** [comment]
GTM

**Comment by phaseinducer** [comment]
Agree but I need it for the EE part and I can't wait the master to be merged in feature/pam :/

**Comment by phaseinducer** [comment]
Replaced by https://github.com/akeneo/pim-community-dev/pull/3078

**Comment by phaseinducer** [comment]
Replaced by https://github.com/akeneo/pim-community-dev/pull/3078

**Pull request closed without merging**
