### PR TITLE
Fixed PIM-4825

### PR DESCRIPTION
**Pull request by antoineguigan**
The description of what the PR does

| Q | A |
| --- | --- |
| Added Specs | No |
| Added Behats | No |
| Travis CI is ok | ? |
| Changelog updated | No |

### CODE REVIEW

**Comment by phaseinducer** [comment]
GTM after specs fixed

**Comment by juliensnz** [comment]
GTM if CI blue

**Comment by nidup** [comment]
Running on:
 - http://core-ci.akeneo.com/job/dci_behat/509/ CE ORM
 - http://core-ci.akeneo.com/job/dci_behat/510/ CE MongoDB
 - http://core-ci.akeneo.com/job/dci_behat/511/ CE ORM
 - http://core-ci.akeneo.com/job/dci_behat/512/ CE MongoDB

**Comment by nidup** [comment]
weird diff with this PR (once pulled locally), i opened another PR here https://github.com/akeneo/pim-community-dev/pull/3870

**Comment by nidup** [comment]
cf other PR and last comment

**Comment by nidup** [comment]
Thank you to spec the case detailed in the original jira issue.

When running the Continuous Integration with EE master and this CE branch it fails with:
```
Problem 1
   - Installation request for akeneo/pim-community-dev dev-PIM-4825 -> satisfiable by akeneo/pim-community-dev[dev-PIM-4825].
   - akeneo/pim-community-dev dev-PIM-4825 requires oro/platform 0.10.7 -> no matching package found.
```

Master/1.5 does not requires oro/platform 0.10.7

So pulled the branch locally and the diff is really weird, contains the composer.json of 1.4 and bunch of changes but does not appear in the github diff.

Thank you to re-open a PR on 1.4 rebased on the last 1.4.

**Pull request closed without merging**
