### PR TITLE
PIM-5387: Fix memory leak in quick export

### PR DESCRIPTION
**Pull request by juliensnz**

### CODE REVIEW

**Comment by rybus** [comment]
GTM

**Comment by nidup** [comment]
Add a line in the changelog in bug fix list them GTM

**Comment by fitn** [comment]
Not fully fixed. As we hydrate non product entities too, families, categories, attributes, attribute options are never detached and create a memory leak.

**Comment by nidup** [comment]
Detach all related entities is another topic, we never clear the whole UOW (we did by the past in deprecated import and had to deal with several issues).
We have another ticket for detaching other entities, question is does the other entities fulfill the memory in an acceptable way, means under max memory that we advise.
This other topic requires extra discussion and investigation.

**Pull request merged**
