### PR TITLE
[TR] fix Grid spin

### PR DESCRIPTION
**Pull request by jmleroux**
| Q                    | A
| -------------------- | ---
| Bug fix?             |y
| New feature?         |n
| BC breaks?           |n
| CI currently passes? |y
| Tests pass?          |y
| Scenarios pass?      |
| Checkstyle issues?*  |n
| PMD issues?**        |n
| Changelog updated?   |n
| Fixed tickets        |
| DB schema updated?   |
| Migration script?    |
| Doc PR               |

### CODE REVIEW

**Comment by sumbobyboys** [comment]
GTM

**Comment by skeleton** [comment]
GTM

**Comment by phaseinducer** [comment]
Wouldn't it be simpler to do a thing like that :
```
$button = $this->spin(function () use ($element) {
    return $element->find('css', 'button');
}
$button->click();
```
?

**Comment by jmleroux** [comment]
@phaseinducer 
the targeted dropdown is not always clickable due to timeout

**Pull request merged**
