### PR TITLE
reset-es-index: Reset Es indexes between tests (behat, integration)

### PR DESCRIPTION
**Pull request by momoss**
**Description (for Contributor and Core Developer)**

Reset Es indexes between tests (behat, integration), the main goal is to not worry about potential new indexes added in the future 

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | -
| Added legacy Behats               | -
| Added acceptance tests            | -
| Added integration tests           | -
| Changelog updated                 | -
| Review and 2 GTM                  | OK
| Micro Demo to the PO (Story only) | -
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

### CODE REVIEW

**Comment by fitn** [comment]
Just a probably silly question but why do we have many clients?

**Comment by solivier** [comment]
@fitn because we have different indexes for different entities. So each client has a different configuration.

**Comment by momoss** [comment]
@fitn actually we have one client by index

**Comment by momoss** [comment]
[Green EE](https://ci.akeneo.com/blue/organizations/jenkins/akeneo%2Fpim-community-dev/detail/PR-7675/2/pipeline/)

**Pull request merged**
