### PR TITLE
Symfony 3.0 upgrade

### PR DESCRIPTION
**Pull request by umpirsky**
I am testing [Symfony Upgrade Fixer](https://github.com/umpirsky/Symfony-Upgrade-Fixer) against several Symfony projects.

Will continue pushing commits to this PR, I hope you will find them useful.

### CODE REVIEW

**Comment by jjanvier** [comment]
Thanks Saša, we appreciate it very much ;)

**Comment by sumbobyboys** [comment]
Wow, awesome work !

**Comment by jjanvier** [comment]
Hello Saša @umpirsky,

Do you want to continue to work on this PR? If no, could you rebase it so that we merged it like that?
And thanks for this really cool contribution :tada:. We really appreciate :smile:

**Comment by umpirsky** [comment]
Hi @jjanvier! :)

I just pushed an update, not much fixed now, just some form types.

Let's wait for the build. :+1:

**Comment by aRn0D** [comment]
hi @umpirsky, can you give feedback on that PR? Can we close it ?

**Comment by umpirsky** [comment]
@aRn0D I rebased on `Apr 14`. As you wish, we can refix again or close, your call. ;)

**Comment by aRn0D** [comment]
@umpirsky I will close it for now. I will try Symfony-Upgrade-Fixer when we will bump Symfony to the version 3.

**Pull request closed without merging**
