### PR TITLE
Lower translation normalizer priority

### PR DESCRIPTION
**Pull request by jmleroux**

### CODE REVIEW

**Comment by a2xchip** [comment]
Just curious what is for?

**Comment by jmleroux** [comment]
Hello @a2xchip 
we had some problems with localizable entities originally created with the custom entity bundle.
After some investigations, we discovered this translation priority problem with the reference data. I make this PR to launch the CI and evaluate the impacts. If it goes well, i will describe the PR a little more ;)

**Comment by aRn0D** [comment]
@jmleroux What is the status of this PR?

**Comment by a2xchip** [comment]
is not rebased i think...

**Pull request closed without merging**
