### PR TITLE
TIP-221: domain layer extraction

### PR DESCRIPTION
**Pull request by jjanvier**
Extracts:
* business classes (located in CatalogBundle\Manager)
* managers without wrong dependencies or weird stuff inside (located in CatalogBundle\Manager)
* factories

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | -
| Added Behats                      | -
| Changelog updated                 | y
| Review and 2 GTM                  |
| Micro Demo to the PO (Story only) | -
| Migration script                  | -
| Tech Doc                          | -

### CODE REVIEW

**Comment by nidup** [comment]
GTM (as you i don't like the Manager folder moved in component but i don't have any other idea except classifying by domain object which will make the stack even more inconsistent)

**Comment by solivier** [comment]
gtm

**Comment by skeleton** [comment]
gtm

**Comment by nidup** [comment]
gtm

**Pull request merged**
