### PR TITLE
[SLA] [TR] PIM-5699: Fix operator is equal to in Job history grid

### PR DESCRIPTION
**Pull request by willy-ahva**
When the user use the "is equal to" operator in code or label filter in export history grid, an error 500 occurs because of a wrong request to database. This fix the alias used to build the query.

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | no
| Added Behats                      | yes
| Changelog updated                 | not yet
| Review and 2 GTM                  |
| Micro Demo to the PO (Story only) |
| Migration script                  |
| Tech Doc                          |

### CODE REVIEW

**Comment by jjanvier** [comment]
GTM

**Comment by pierallard** [comment]
GTM

**Comment by solivier** [comment]
gtm

**Comment by juliensnz** [comment]
GTM

**Pull request merged**
