### PR TITLE
OptionCodeUpdatedQueryGenerator fix

### PR DESCRIPTION
**Pull request by dmkaaa**
PIM version: 1.7 (other versions can be also affected)

Option code updated query generator must update only those products that have given option selected, not all the products with given attribute.

### CODE REVIEW

**Comment by pierallard** [comment]
Hi @dmkaaa !
Thanks a lot for your contribution !
I tried to reproduce your bug in 1.7... And I don't know how you change an attribute option code! Indeed, this functionality was removed in latest versions.
IMHO, all the class you update should be removed because it's useless :)
Can you provide to this PR a list of actions to to on a 1.7 environment to see the bug happening?
Thanks!

**Comment by dmkaaa** [comment]
Hello!

This query is being also executed when you add a new option to a simple select attribute.

**Comment by pierallard** [comment]
Hi !
I still not understand what is the bug.
Can you provide to this PR a list of actions to to on a 1.7 environment to see the bug happening?
Like:
- Create a new attribute
- Create a new attribute option called "xxx"...

Thanks!

**Comment by dmkaaa** [comment]
Hi!

Actions are following (data source must be MongoDB):
1. Create simple select attribute, for example, color.
2. Add an option with code red to the attribute
3. Add this attribute to some products and select the option mentioned above. The products will now have normalizedData.color.code = red property in Mongo collection.
4. Add another option to the attribute. For example, green.
5. Now normalizedData.color.code of all products (that have color attribute) will change to green.

**Comment by pierallard** [comment]
OK ! I got it ! You're completely right, there is a bug.
I have no remarks on your current PR, but I will add a test to prevent have it again in another upcoming version ;)

**Comment by pierallard** [comment]
Hi @dmkaaa !
Thanks a lot for this bugfix, it's very appreciated !
It was just merged, congratulations ;)

Pierre

**Comment by mickaelandrieu** [comment]
Congratulations @dmkaaa, Your PR has been merged !

🎉 Again, thank you for your contribution !

You can now claim your "Core contributor" badge on [Badger](http://badger.akeneo.com).

If you wish to contribute again, don't hesitate to look at our github project board where we labeled [all kinds of tasks to take on](https://github.com/akeneo/pim-community-dev/projects/1) !

**Pull request merged**
