### PR TITLE
Fix randoms on empty grid testing

### PR DESCRIPTION
**Pull request by phaseinducer**
Attempt to fix this random fatal :
```
PHP Fatal error:  Call to a member function find() on a non-object in /var/lib/jenkins/distributed-ci/builds/pim-community-dev_1265/features/Context/Page/Base/Grid.php on line 272
```

### CODE REVIEW

**Comment by jjanvier** [comment]
gtm

**Comment by jjanvier** [comment]
just remember to remove the 20 on master

**Comment by solivier** [comment]
gtm

**Comment by juliensnz** [comment]
GTM

**Pull request merged**
