### PR TITLE
[DOC] Correct a dead link

### PR DESCRIPTION
**Pull request by anaelChardan**
**Description (for Contributor and Core Developer)**

What does this Pull Request do? reference the related issue?

Just correct links into the README (including a dead link and two old http links)

### CODE REVIEW

**Comment by pierallard** [comment]
GTM

**Comment by damien-carcel** [comment]
GTM

**Comment by jjanvier** [comment]
Thanks @anaelChardan 
First PR merged on the PIM \o/

**Comment by anaelChardan** [comment]
Yeah :D

**Pull request merged**
