### PR TITLE
Export products performance

### PR DESCRIPTION
**Pull request by Hocdoc**
Most of our products have about 250 attributes, but we only have few price attributes.
With this small change exporting products is 10% faster for us.

### CODE REVIEW

**Comment by juliensnz** [comment]
Hello Hocdoc. Thanks for this contribution ! I run the CI on this PR and try to merge it ASAP !

**Comment by ClementGautier** [comment]
GTM

**Comment by jjanvier** [comment]
GTM
So simple and obvious :astonished:! thanks for the contribution @Hocdoc :)

**Comment by skeleton** [comment]
GTM ! Thanks for your contribution :)

**Comment by solivier** [comment]
GTM

**Pull request merged**
