### PR TITLE
TR PIM-4943 Use a stable MongoDB bundle version

### PR DESCRIPTION
**Pull request by BitOne**
| Q                  | A
| ------------------ | ---
| Migration script?  | N.A.
| Behats             | OK
| Specs & Static     | OK
| Changelog updated  | N.A.

### CODE REVIEW

**Comment by jmleroux** [comment]
GTM

**Comment by nidup** [comment]
GTM

**Comment by jjanvier** [comment]
GTM

**Comment by jjanvier** [comment]
closed in favor of https://github.com/akeneo/pim-community-dev/pull/3356

**Pull request closed without merging**
