### PR TITLE
Allows ctrl-c for stopping the php process in docker-compose

### PR DESCRIPTION
**Pull request by tseho**
**Description (for Contributor and Core Developer)**

Do you hate when you start a consumer with docker-compose and you cannot stop it ?

Screenshot_2021-04-13_17-19-41

~Have you tried turning your computer off and on again?~

---

Now, with this PR, it will work.

Screenshot_2021-04-13_17-18-43

**How**

I'm simply proposing to use the option `init: true` see https://docs.docker.com/compose/compose-file/compose-file-v3/#init
It's only possible since https://github.com/akeneo/pim-community-dev/pull/14303, thanks to our dear @jmleroux 

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | -
| Added legacy Behats               | -
| Added acceptance tests            | -
| Added integration tests           | -
| Changelog updated                 | -
| Review and 2 GTM                  | Todo
| Micro Demo to the PO (Story only) | -
| Migration script                  | -
| Tech Doc                          | -

### CODE REVIEW

**Comment by jmleroux** [comment]
> We could use the option init: true see https://docs.docker.com/compose/compose-file/compose-file-v3/#init
But it's only working since docker-compose format 3.7.

And why is it not possible to use the 3.7 format?

**Comment by tseho** [comment]
> And why is it not possible to use the 3.7 format?
That's a great question.

It's easy to change it in the docker-compose file buuuuuut there is a small issue.
docker-compose format 3.7 is supported since docker-compose v1.22.0, see https://docs.docker.com/compose/release-notes/#1220

And it's where the fun begins.
For example, in circleci, we are using the image `ubuntu-1604:201903-01` which was built at the time with https://github.com/CircleCI-Public/circleci-dockerfiles/blob/8e8eb0462471a6693fa8d1aee36bc5c9784d0793/buildpack-deps/images/xenial/Dockerfile#L70-L74
(Meaning the "latest" version at the time was included, not updated since)
I've tried, it does not work with our current image https://app.circleci.com/pipelines/github/akeneo/pim-community-dev/21452/workflows/7fe11d47-f836-4b77-b4df-d00eb2575e31/jobs/88219
So, we would have to change the image used by our CI.
And who knows what else ?

**Comment by BitOne** [comment]
Clearly not really fan of changing the init for this reason, as it's not really blocking (a kill command would exit the process without issue).

**Comment by pchasle** [comment]
Since @jmleroux migrated docker-compose to 3.7, does this means we can add the option `init: true` ?

**Comment by tseho** [comment]
@pchasle yes, I will update the pr accordingly asap.

**Comment by tseho** [comment]
I've updated the PR, and went back to the initial solution with `init: true`

**Review by BitOne — APPROVED** [review]

**Review by nmarniesse — APPROVED** [review]
:+1:

**Review by jmleroux — APPROVED** [review]

**Pull request merged**
