### PR TITLE
PIM-7509: Fix search on categories with product models

### PR DESCRIPTION
**Pull request by SamirBoulil**
**Context:**

Following the wonderful work made by @ahocquard https://github.com/akeneo/pim-community-dev/pull/8312 on improving the
scalability of the search on categories, the "aggregated" search of
product models with categories was not working properly.

**Problem:**

In his refactoring, he introduces a new way to filter on categories on
the product grid. Before his changes when a user would select a category
in the category tree with the "include children" flag set to "yes". The
whole list of categories would be passed on to the back-end (category
selected + children) instead of using the IN_CHILDREN operator available
with the category filter.

@ahocquard fixes does just that, it uses the IN_CHILDREN operator
instead of the IN_LIST with a big list of category codes.

**Solution:**

Make sure the PQB of products and product models in enrich takes this new
case into account and aggregates the result when a filter with
"IN_CHILDREN" is used.

**Description (for Contributor and Core Developer)**

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | Ok
| Added legacy Behats               | -
| Added acceptance tests            | -
| Added integration tests           | -
| Changelog updated                 | Ok
| Review and 2 GTM                  | Ok
| Micro Demo to the PO (Story only) | Ok
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

### CODE REVIEW

**Comment by SamirBoulil** [comment]
Linked to https://github.com/akeneo/pim-community-dev/pull/8312

**Comment by ahocquard** [comment]
@SamirBoulil it seems not related to my work at all, as I didn't touch the PQB and merged it on master and not in 2.3.

Also, IN_CHILDREN operator still uses a list of category codes in the query to ES, because there is no way to do it differently according to the current indexation.

**Comment by SamirBoulil** [comment]
That's wierd, that's not what I've seen. there is clearly the use of an IN_CHILDREN operator when filtering on categories with the datagrid.

**Comment by ahocquard** [comment]
My PR was about the category tree, not the category filter in the datagrid.
And it's on master. Probably a different PR introduced the bug.

**Pull request merged**
