### PR TITLE
Remove measure bundle from composer

### PR DESCRIPTION
**Pull request by solivier**
| Q                                 | A
| --------------------------------- | ---
| Review and 2 GTM                  | Y

### CODE REVIEW

**Comment by pierallard** [comment]
GTM

**Comment by ClementGautier** [comment]
GTM

**Comment by nidup** [comment]
https://www.youtube.com/watch?v=shMT6kzFIi0 GTM

**Comment by nidup** [comment]
closed in favor of https://github.com/akeneo/pim-community-dev/pull/4882

**Pull request closed without merging**
