### PR TITLE
Remove old product validator

### PR DESCRIPTION
**Pull request by solivier**
| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | No
| Added Behats                      | No
| Changelog updated                 | Yes
| Review and 2 GTM                  | Yes

- [ ] Add changelog

### CODE REVIEW

**Comment by juliensnz** [comment]
GTM

**Comment by grena** [comment]
GTM

**Comment by skeleton** [comment]
GTM

**Comment by nidup** [comment]
GTM

**Pull request merged**
