### PR TITLE
Run elasticsearch container in development mode

### PR DESCRIPTION
**Pull request by aaa2000**
**Description (for Contributor and Core Developer)**

Given that according to the documentation, the docker compose file is used for development and testing purposes only, the elasticsearch container can run in development mode and the documentation https://docs.akeneo.com/master/install_pim/docker/installation_docker.html#elasticsearch could be simplified because the procedure is for develpment mode. See https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-dev-mode

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | -
| Added Behats                      | -
| Added integration tests           | -
| Changelog updated                 | -
| Review and 2 GTM                  | Todo
| Micro Demo to the PO (Story only) | -
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

### CODE REVIEW

**Comment by damien-carcel** [comment]
Hello @aaa2000.

Thank you so much for this pull request. It will indeed ease a lot the usage of ES through Docker.

Instead of using `-`, could you please update your PR with
```yaml
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      discovery.type: 'single-node'
```
This is just to keep environment variables written the same way than in the rest of the compose file.

Once your PR merged, I'll update our enterprise edition and the documentation.

Regards,
Damien

**Comment by aaa2000** [comment]
@damien-carcel done

**Comment by damien-carcel** [comment]
And it is merged. Thanki you so much for your contrib @aaa2000 .
I'll update the master documentation to reflect this change as soon as possible.
Regards,
Damien

**Comment by damien-carcel** [comment]
And I'll add your contrib to the changelog too 😃.

**Pull request merged**
